// GENERATED by scripts/generate-tap-dot.mjs. Do not edit by hand.

/** A tap-highlight style: the preview gradient matches the baked ffmpeg frames. */
export interface TapPreset {
  id: string;
  label: string;
  gradient: string;
}

export const TAP_PRESETS: TapPreset[] = [
  {
    id: "glow-light",
    label: "Soft glow, light",
    gradient:
      "radial-gradient(circle closest-side, rgba(255, 255, 255, 0.95) 0%, rgba(255, 255, 255, 0.55) 45%, rgba(255, 255, 255, 0) 70%)",
  },
  {
    id: "glow-dark",
    label: "Soft glow, dark",
    gradient:
      "radial-gradient(circle closest-side, rgba(17, 17, 17, 0.85) 0%, rgba(17, 17, 17, 0.6) 42%, rgba(255, 255, 255, 0.7) 54%, rgba(255, 255, 255, 0) 70%)",
  },
  {
    id: "glow-blue",
    label: "Soft glow, blue",
    gradient:
      "radial-gradient(circle closest-side, rgba(64, 156, 255, 0.95) 0%, rgba(64, 156, 255, 0.6) 45%, rgba(64, 156, 255, 0) 70%)",
  },
  {
    id: "ring-light",
    label: "Ring, light",
    gradient:
      "radial-gradient(circle closest-side, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.05) 42%, rgba(255, 255, 255, 0.9) 52%, rgba(255, 255, 255, 0.9) 60%, rgba(255, 255, 255, 0) 70%)",
  },
  {
    id: "ring-dark",
    label: "Ring, dark",
    gradient:
      "radial-gradient(circle closest-side, rgba(17, 17, 17, 0) 0%, rgba(17, 17, 17, 0.06) 42%, rgba(17, 17, 17, 0.92) 52%, rgba(17, 17, 17, 0.88) 60%, rgba(17, 17, 17, 0) 70%)",
  },
];

export const DEFAULT_TAP_PRESET_ID = "glow-light";
