// GENERATED by scripts/generate-tap-dot.mjs. Do not edit by hand.

/** A tap-highlight style (shape): alpha stops over half the element, closest-side. */
export interface TapStyle {
  id: string;
  label: string;
  alphaStops: [number, number][];
}

/** A tap-highlight colour, applied to any style. */
export interface TapColor {
  id: string;
  label: string;
  rgb: [number, number, number];
}

export const TAP_STYLES: TapStyle[] = [
  {
    id: "glow",
    label: "Soft glow",
    alphaStops: [
      [0, 0.95],
      [0.45, 0.55],
      [0.7, 0],
    ],
  },
  {
    id: "dot",
    label: "Dot",
    alphaStops: [
      [0, 0.95],
      [0.5, 0.95],
      [0.62, 0],
    ],
  },
  {
    id: "ring",
    label: "Ring",
    alphaStops: [
      [0, 0],
      [0.42, 0.05],
      [0.52, 0.9],
      [0.6, 0.9],
      [0.7, 0],
    ],
  },
  {
    id: "target",
    label: "Dot and ring",
    alphaStops: [
      [0, 0.95],
      [0.18, 0.95],
      [0.26, 0],
      [0.5, 0],
      [0.56, 0.9],
      [0.64, 0.9],
      [0.7, 0],
    ],
  },
];

export const TAP_COLORS: TapColor[] = [
  { id: "light", label: "Light", rgb: [255, 255, 255] },
  { id: "dark", label: "Dark", rgb: [17, 17, 17] },
  { id: "blue", label: "Blue", rgb: [64, 156, 255] },
  { id: "red", label: "Red", rgb: [255, 59, 48] },
  { id: "terracotta", label: "Terracotta", rgb: [226, 114, 91] },
];

export const DEFAULT_TAP_STYLE_ID = "glow";
export const DEFAULT_TAP_COLOR_ID = "light";
