import type { Theme } from "../../../theme/tokens";

/** Bundled looks for each 3D background: 9 per look (p1-p5 light, p6-p9 dark), applied wholesale by the inspector's preset tiles like the shader packs (docs/backgrounds.md; the same luminance bands and AA rules apply to every geometry colour AND the backing). `backing` is the camera-locked fill stamped behind the geometry on apply; the schema accepts any 2D background there, presets keep it a flat colour. */

export interface Scene3dBackgroundPreset {
  /** Look-scoped id (p1..p9); pair with the look id, never unique alone. */
  id: string;
  name: string;
  /** Light presets carry black text at AA; dark presets carry white. */
  mode: "light" | "dark";
  /** AA-checked text colour over every stop (card metadata / contrast hints). */
  textColor: string;
  /** One hex per geometry colour slot, in slot order. */
  colors: string[];
  /** Flat backing colour stamped as `backing: { type: "color" }` on apply. */
  backing: string;
  speed?: number;
  params?: Record<string, number>;
}

export const SCENE3D_BACKGROUND_PRESETS: Record<string, Scene3dBackgroundPreset[]> = {
  "grid-plain": [
    {
      id: "p1",
      name: "Lord Howe",
      mode: "light",
      textColor: "#000000",
      colors: ["#7ccae3"],
      backing: "#e2f3fb",
      speed: 0.4,
      params: { spacing: 1.2, height: -2, clearRadius: 4, fadeRadius: 44, drift: 1, opacity: 0.8 },
    },
    {
      id: "p2",
      name: "Currumbin",
      mode: "light",
      textColor: "#000000",
      colors: ["#d6bd74"],
      backing: "#f5f0dc",
      speed: 0.35,
      params: {
        spacing: 1.6,
        height: -2.2,
        clearRadius: 5,
        fadeRadius: 50,
        drift: 0.6,
        opacity: 0.7,
      },
    },
    {
      id: "p3",
      name: "Daylesford",
      mode: "light",
      textColor: "#000000",
      colors: ["#73d383"],
      backing: "#ddf6e4",
      speed: 0.45,
      params: {
        spacing: 0.9,
        height: -1.8,
        clearRadius: 3.5,
        fadeRadius: 38,
        drift: 1.4,
        opacity: 0.75,
      },
    },
    {
      id: "p4",
      name: "Pemberton",
      mode: "light",
      textColor: "#000000",
      colors: ["#82d272"],
      backing: "#e3f5dd",
      speed: 0.3,
      params: {
        spacing: 2.2,
        height: -2.5,
        clearRadius: 6,
        fadeRadius: 60,
        drift: 0.8,
        opacity: 0.85,
      },
    },
    {
      id: "p5",
      name: "Ceduna",
      mode: "light",
      textColor: "#000000",
      colors: ["#ffaa8e"],
      backing: "#feede4",
      speed: 0.5,
      params: {
        spacing: 1.3,
        height: -2,
        clearRadius: 4.5,
        fadeRadius: 46,
        drift: 1.1,
        opacity: 0.7,
      },
    },
    {
      id: "p6",
      name: "Gulf Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#3b5c7d"],
      backing: "#0d1218",
      speed: 0.4,
      params: { spacing: 1.2, height: -2, clearRadius: 4, fadeRadius: 44, drift: 1, opacity: 0.8 },
    },
    {
      id: "p7",
      name: "Tanami",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#765137"],
      backing: "#17110d",
      speed: 0.35,
      params: {
        spacing: 1.8,
        height: -2.4,
        clearRadius: 5.5,
        fadeRadius: 55,
        drift: 0.7,
        opacity: 0.9,
      },
    },
    {
      id: "p8",
      name: "Oodnadatta",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#8b424f"],
      backing: "#1a0f10",
      speed: 0.45,
      params: {
        spacing: 1,
        height: -1.8,
        clearRadius: 3.5,
        fadeRadius: 40,
        drift: 1.3,
        opacity: 0.75,
      },
    },
    {
      id: "p9",
      name: "Silverton",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#694997"],
      backing: "#14101c",
      speed: 0.3,
      params: {
        spacing: 1.4,
        height: -2.1,
        clearRadius: 4.5,
        fadeRadius: 48,
        drift: 0.9,
        opacity: 0.85,
      },
    },
  ],
  "grid-shell": [
    {
      id: "p1",
      name: "Heron Island",
      mode: "light",
      textColor: "#000000",
      colors: ["#63c1c9"],
      backing: "#dff4f8",
      speed: 0.4,
      params: { radius: 22, latCount: 16, lonCount: 24, horizonBias: 0.5, drift: 1, opacity: 0.9 },
    },
    {
      id: "p2",
      name: "Kiama",
      mode: "light",
      textColor: "#000000",
      colors: ["#75baeb"],
      backing: "#e4f2fe",
      speed: 0.35,
      params: {
        radius: 19,
        latCount: 20,
        lonCount: 28,
        horizonBias: 0.35,
        drift: 1.3,
        opacity: 0.85,
      },
    },
    {
      id: "p3",
      name: "Yamba",
      mode: "light",
      textColor: "#000000",
      colors: ["#61c5a3"],
      backing: "#ddf5ef",
      speed: 0.45,
      params: {
        radius: 26,
        latCount: 12,
        lonCount: 18,
        horizonBias: 0.6,
        drift: 0.7,
        opacity: 0.95,
      },
    },
    {
      id: "p4",
      name: "Busselton",
      mode: "light",
      textColor: "#000000",
      colors: ["#99b0ff"],
      backing: "#e9f0ff",
      speed: 0.3,
      params: {
        radius: 21,
        latCount: 18,
        lonCount: 30,
        horizonBias: 0.45,
        drift: 0.9,
        opacity: 0.85,
      },
    },
    {
      id: "p5",
      name: "Seacliff",
      mode: "light",
      textColor: "#000000",
      colors: ["#ff92b4"],
      backing: "#ffebf0",
      speed: 0.5,
      params: {
        radius: 24,
        latCount: 14,
        lonCount: 20,
        horizonBias: 0.55,
        drift: 1.1,
        opacity: 0.9,
      },
    },
    {
      id: "p6",
      name: "Birdsville",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#815a3d"],
      backing: "#17110d",
      speed: 0.4,
      params: { radius: 22, latCount: 16, lonCount: 24, horizonBias: 0.5, drift: 1, opacity: 0.95 },
    },
    {
      id: "p7",
      name: "Gibson",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#994a57"],
      backing: "#1a0f10",
      speed: 0.35,
      params: { radius: 20, latCount: 19, lonCount: 28, horizonBias: 0.4, drift: 1.2, opacity: 1 },
    },
    {
      id: "p8",
      name: "Marree",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#416589"],
      backing: "#0e1219",
      speed: 0.45,
      params: {
        radius: 25,
        latCount: 12,
        lonCount: 16,
        horizonBias: 0.6,
        drift: 0.8,
        opacity: 0.9,
      },
    },
    {
      id: "p9",
      name: "Kalbarri Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#7e4da0"],
      backing: "#170f1b",
      speed: 0.3,
      params: {
        radius: 22,
        latCount: 17,
        lonCount: 26,
        horizonBias: 0.5,
        drift: 1.4,
        opacity: 0.95,
      },
    },
  ],
  "grid-hall": [
    {
      id: "p1",
      name: "Jenolan",
      mode: "light",
      textColor: "#000000",
      colors: ["#70bce2"],
      backing: "#e3f2fd",
      speed: 0.4,
      params: {
        width: 16,
        depth: 28,
        height: 12,
        spacing: 1.2,
        clearRadius: 4,
        drift: 1,
        opacity: 0.9,
      },
    },
    {
      id: "p2",
      name: "Naracoorte",
      mode: "light",
      textColor: "#000000",
      colors: ["#d2ae68"],
      backing: "#f6f0de",
      speed: 0.35,
      params: {
        width: 20,
        depth: 34,
        height: 10,
        spacing: 1.6,
        clearRadius: 5,
        drift: 0.7,
        opacity: 0.85,
      },
    },
    {
      id: "p3",
      name: "Buchan",
      mode: "light",
      textColor: "#000000",
      colors: ["#61c694"],
      backing: "#ddf6eb",
      speed: 0.45,
      params: {
        width: 14,
        depth: 24,
        height: 14,
        spacing: 1,
        clearRadius: 3.5,
        drift: 1.3,
        opacity: 0.9,
      },
    },
    {
      id: "p4",
      name: "Capricorn Coast",
      mode: "light",
      textColor: "#000000",
      colors: ["#67c0d1"],
      backing: "#e0f3f9",
      speed: 0.3,
      params: {
        width: 22,
        depth: 36,
        height: 12,
        spacing: 1.8,
        clearRadius: 6,
        drift: 0.8,
        opacity: 0.95,
      },
    },
    {
      id: "p5",
      name: "Margaret River",
      mode: "light",
      textColor: "#000000",
      colors: ["#63c863"],
      backing: "#e0f6dd",
      speed: 0.5,
      params: {
        width: 15,
        depth: 26,
        height: 9,
        spacing: 1.1,
        clearRadius: 4.5,
        drift: 1.1,
        opacity: 0.85,
      },
    },
    {
      id: "p6",
      name: "Wombeyan",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#45648f"],
      backing: "#0e1219",
      speed: 0.4,
      params: {
        width: 16,
        depth: 28,
        height: 12,
        spacing: 1.2,
        clearRadius: 4,
        drift: 1,
        opacity: 0.95,
      },
    },
    {
      id: "p7",
      name: "Yarrangobilly",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#336d59"],
      backing: "#0a1411",
      speed: 0.35,
      params: {
        width: 14,
        depth: 24,
        height: 15,
        spacing: 1,
        clearRadius: 3.5,
        drift: 1.2,
        opacity: 1,
      },
    },
    {
      id: "p8",
      name: "Abercrombie",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#85583f"],
      backing: "#17110c",
      speed: 0.45,
      params: {
        width: 21,
        depth: 36,
        height: 10,
        spacing: 1.7,
        clearRadius: 5.5,
        drift: 0.7,
        opacity: 0.9,
      },
    },
    {
      id: "p9",
      name: "Mole Creek",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#6f52a9"],
      backing: "#15101c",
      speed: 0.3,
      params: {
        width: 17,
        depth: 30,
        height: 13,
        spacing: 1.3,
        clearRadius: 4.5,
        drift: 0.9,
        opacity: 0.95,
      },
    },
  ],
  "contour-field": [
    {
      id: "p1",
      name: "Dorrigo",
      mode: "light",
      textColor: "#000000",
      colors: ["#62c873"],
      backing: "#ddf6e4",
      speed: 0.4,
      params: {
        levels: 10,
        hilliness: 1,
        scale: 14,
        height: -2,
        clearRadius: 4,
        fadeRadius: 44,
        drift: 1,
        opacity: 0.9,
      },
    },
    {
      id: "p2",
      name: "Barrington",
      mode: "light",
      textColor: "#000000",
      colors: ["#72c662"],
      backing: "#e3f5dd",
      speed: 0.35,
      params: {
        levels: 13,
        hilliness: 1.3,
        scale: 12,
        height: -1.8,
        clearRadius: 3.5,
        fadeRadius: 40,
        drift: 1.2,
        opacity: 0.85,
      },
    },
    {
      id: "p3",
      name: "Monaro",
      mode: "light",
      textColor: "#000000",
      colors: ["#cbb164"],
      backing: "#f5f0dc",
      speed: 0.45,
      params: {
        levels: 8,
        hilliness: 0.8,
        scale: 18,
        height: -2.2,
        clearRadius: 5,
        fadeRadius: 52,
        drift: 0.7,
        opacity: 0.9,
      },
    },
    {
      id: "p4",
      name: "Liverpool Plains",
      mode: "light",
      textColor: "#000000",
      colors: ["#abbb5c"],
      backing: "#edf3da",
      speed: 0.3,
      params: {
        levels: 11,
        hilliness: 0.9,
        scale: 16,
        height: -2.4,
        clearRadius: 5.5,
        fadeRadius: 55,
        drift: 0.8,
        opacity: 0.95,
      },
    },
    {
      id: "p5",
      name: "Darling Downs",
      mode: "light",
      textColor: "#000000",
      colors: ["#e0a86f"],
      backing: "#f9eee0",
      speed: 0.5,
      params: {
        levels: 9,
        hilliness: 1.1,
        scale: 14,
        height: -2,
        clearRadius: 4.5,
        fadeRadius: 46,
        drift: 1.1,
        opacity: 0.85,
      },
    },
    {
      id: "p6",
      name: "Breadknife",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#3e6783"],
      backing: "#0d1218",
      speed: 0.4,
      params: {
        levels: 10,
        hilliness: 1,
        scale: 14,
        height: -2,
        clearRadius: 4,
        fadeRadius: 44,
        drift: 1,
        opacity: 0.95,
      },
    },
    {
      id: "p7",
      name: "Warrego",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#865740"],
      backing: "#17110c",
      speed: 0.35,
      params: {
        levels: 13,
        hilliness: 1.4,
        scale: 12,
        height: -1.8,
        clearRadius: 3.5,
        fadeRadius: 40,
        drift: 1.3,
        opacity: 1,
      },
    },
    {
      id: "p8",
      name: "Diamantina",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#326c5e"],
      backing: "#0a1412",
      speed: 0.45,
      params: {
        levels: 8,
        hilliness: 0.8,
        scale: 19,
        height: -2.3,
        clearRadius: 5,
        fadeRadius: 55,
        drift: 0.7,
        opacity: 0.9,
      },
    },
    {
      id: "p9",
      name: "Cooper Creek",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#706134"],
      backing: "#15120b",
      speed: 0.3,
      params: {
        levels: 12,
        hilliness: 1.1,
        scale: 15,
        height: -2.1,
        clearRadius: 4.5,
        fadeRadius: 48,
        drift: 0.9,
        opacity: 0.95,
      },
    },
  ],
};

/** The anchor preset backing a 3D look's Theme tile and live-derived colours: `p1` for light themes, `p6` for dark (the shader-pack convention). */
export function scene3dThemeAnchor(
  look: string,
  theme: Theme,
): Scene3dBackgroundPreset | undefined {
  const mode = theme.mode ?? "dark";
  return SCENE3D_BACKGROUND_PRESETS[look]?.find((p) => p.id === (mode === "light" ? "p1" : "p6"));
}
