import type { Theme } from "../../../theme/tokens";

/** Bundled looks for each 3D background: 9 per look (p1-p5 light, p6-p9 dark), applied wholesale by the inspector's preset tiles like the shader packs (docs/backgrounds.md; the same luminance bands and AA rules apply to every geometry colour AND the backing). `backing` is the camera-locked fill stamped behind the geometry on apply; the schema accepts any 2D background there, presets keep it a flat colour. */

export interface Scene3dBackgroundPreset {
  /** Look-scoped id (p1..p9); pair with the look id, never unique alone. */
  id: string;
  name: string;
  /** Light presets carry black text at AA; dark presets carry white. */
  mode: "light" | "dark";
  /** AA-checked text colour over every stop (card metadata / contrast hints). */
  textColor: string;
  /** One hex per geometry colour slot, in slot order. */
  colors: string[];
  /** Flat backing colour stamped as `backing: { type: "color" }` on apply. */
  backing: string;
  speed?: number;
  params?: Record<string, number>;
}

export const SCENE3D_BACKGROUND_PRESETS: Record<string, Scene3dBackgroundPreset[]> = {
  "grid-plain": [
    {
      id: "p1",
      name: "Lord Howe",
      mode: "light",
      textColor: "#000000",
      colors: ["#7ccae3"],
      backing: "#e2f3fb",
      speed: 1,
      params: {
        spacing: 1.2,
        height: -1.3,
        clearRadius: 4,
        fadeRadius: 40,
        drift: 1,
        opacity: 0.8,
      },
    },
    {
      id: "p2",
      name: "Currumbin",
      mode: "light",
      textColor: "#000000",
      colors: ["#d6bd74"],
      backing: "#f5f0dc",
      speed: 0.7,
      params: {
        spacing: 1.6,
        height: -1.6,
        clearRadius: 5,
        fadeRadius: 48,
        drift: 0.7,
        opacity: 0.75,
      },
    },
    {
      id: "p3",
      name: "Daylesford",
      mode: "light",
      textColor: "#000000",
      colors: ["#73d383"],
      backing: "#ddf6e4",
      speed: 0.9,
      params: {
        spacing: 0.9,
        height: -1.2,
        clearRadius: 3.5,
        fadeRadius: 34,
        drift: 1.3,
        opacity: 0.75,
      },
    },
    {
      id: "p4",
      name: "Pemberton",
      mode: "light",
      textColor: "#000000",
      colors: ["#82d272"],
      backing: "#e3f5dd",
      speed: 0.6,
      params: {
        spacing: 2.1,
        height: -1.8,
        clearRadius: 6,
        fadeRadius: 52,
        drift: 0.8,
        opacity: 0.85,
      },
    },
    {
      id: "p5",
      name: "Ceduna",
      mode: "light",
      textColor: "#000000",
      colors: ["#ffaa8e"],
      backing: "#feede4",
      speed: 1.2,
      params: {
        spacing: 1.3,
        height: -1.3,
        clearRadius: 4.5,
        fadeRadius: 42,
        drift: 1.1,
        opacity: 0.7,
      },
    },
    {
      id: "p6",
      name: "Gulf Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#3b5c7d"],
      backing: "#0d1218",
      speed: 1,
      params: {
        spacing: 1.2,
        height: -1.3,
        clearRadius: 4,
        fadeRadius: 40,
        drift: 1,
        opacity: 0.85,
      },
    },
    {
      id: "p7",
      name: "Tanami",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#765137"],
      backing: "#17110d",
      speed: 0.7,
      params: {
        spacing: 1.7,
        height: -1.5,
        clearRadius: 5,
        fadeRadius: 50,
        drift: 0.7,
        opacity: 0.9,
      },
    },
    {
      id: "p8",
      name: "Oodnadatta",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#8b424f"],
      backing: "#1a0f10",
      speed: 0.9,
      params: {
        spacing: 0.95,
        height: -1.1,
        clearRadius: 3.5,
        fadeRadius: 36,
        drift: 1.25,
        opacity: 0.8,
      },
    },
    {
      id: "p9",
      name: "Silverton",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#694997"],
      backing: "#14101c",
      speed: 0.6,
      params: {
        spacing: 1.4,
        height: -1.4,
        clearRadius: 4.5,
        fadeRadius: 44,
        drift: 0.9,
        opacity: 0.85,
      },
    },
  ],
  "grid-shell": [
    {
      id: "p1",
      name: "Heron Island",
      mode: "light",
      textColor: "#000000",
      colors: ["#63c1c9"],
      backing: "#dff4f8",
      speed: 1,
      params: { radius: 18, latCount: 11, lonCount: 32, horizonBias: 0.5, drift: 1, opacity: 0.7 },
    },
    {
      id: "p2",
      name: "Kiama",
      mode: "light",
      textColor: "#000000",
      colors: ["#75baeb"],
      backing: "#e4f2fe",
      speed: 0.7,
      params: {
        radius: 15,
        latCount: 14,
        lonCount: 38,
        horizonBias: 0.35,
        drift: 1.3,
        opacity: 0.65,
      },
    },
    {
      id: "p3",
      name: "Yamba",
      mode: "light",
      textColor: "#000000",
      colors: ["#61c5a3"],
      backing: "#ddf5ef",
      speed: 0.9,
      params: {
        radius: 22,
        latCount: 9,
        lonCount: 26,
        horizonBias: 0.62,
        drift: 0.7,
        opacity: 0.75,
      },
    },
    {
      id: "p4",
      name: "Busselton",
      mode: "light",
      textColor: "#000000",
      colors: ["#99b0ff"],
      backing: "#e9f0ff",
      speed: 0.6,
      params: {
        radius: 17,
        latCount: 13,
        lonCount: 44,
        horizonBias: 0.45,
        drift: 0.9,
        opacity: 0.65,
      },
    },
    {
      id: "p5",
      name: "Seacliff",
      mode: "light",
      textColor: "#000000",
      colors: ["#ff92b4"],
      backing: "#ffebf0",
      speed: 1.2,
      params: {
        radius: 20,
        latCount: 10,
        lonCount: 28,
        horizonBias: 0.55,
        drift: 1.1,
        opacity: 0.7,
      },
    },
    {
      id: "p6",
      name: "Birdsville",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#815a3d"],
      backing: "#17110d",
      speed: 1,
      params: { radius: 18, latCount: 11, lonCount: 32, horizonBias: 0.5, drift: 1, opacity: 0.75 },
    },
    {
      id: "p7",
      name: "Gibson",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#994a57"],
      backing: "#1a0f10",
      speed: 0.7,
      params: {
        radius: 16,
        latCount: 14,
        lonCount: 40,
        horizonBias: 0.4,
        drift: 1.2,
        opacity: 0.8,
      },
    },
    {
      id: "p8",
      name: "Marree",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#416589"],
      backing: "#0e1219",
      speed: 0.9,
      params: { radius: 23, latCount: 9, lonCount: 24, horizonBias: 0.6, drift: 0.8, opacity: 0.7 },
    },
    {
      id: "p9",
      name: "Kalbarri Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#7e4da0"],
      backing: "#170f1b",
      speed: 0.6,
      params: {
        radius: 18,
        latCount: 12,
        lonCount: 36,
        horizonBias: 0.5,
        drift: 1.4,
        opacity: 0.75,
      },
    },
  ],
  "grid-hall": [
    {
      id: "p1",
      name: "Jenolan",
      mode: "light",
      textColor: "#000000",
      colors: ["#70bce2"],
      backing: "#e3f2fd",
      speed: 1,
      params: {
        width: 19,
        depth: 48,
        height: 12,
        spacing: 1.2,
        clearRadius: 3.5,
        drift: 1,
        opacity: 0.9,
      },
    },
    {
      id: "p2",
      name: "Naracoorte",
      mode: "light",
      textColor: "#000000",
      colors: ["#d2ae68"],
      backing: "#f6f0de",
      speed: 0.7,
      params: {
        width: 23,
        depth: 58,
        height: 10,
        spacing: 1.6,
        clearRadius: 4.5,
        drift: 0.7,
        opacity: 0.85,
      },
    },
    {
      id: "p3",
      name: "Buchan",
      mode: "light",
      textColor: "#000000",
      colors: ["#61c694"],
      backing: "#ddf6eb",
      speed: 0.9,
      params: {
        width: 15,
        depth: 40,
        height: 14,
        spacing: 1,
        clearRadius: 3,
        drift: 1.3,
        opacity: 0.9,
      },
    },
    {
      id: "p4",
      name: "Capricorn Coast",
      mode: "light",
      textColor: "#000000",
      colors: ["#67c0d1"],
      backing: "#e0f3f9",
      speed: 0.6,
      params: {
        width: 26,
        depth: 62,
        height: 12,
        spacing: 1.8,
        clearRadius: 5,
        drift: 0.8,
        opacity: 0.95,
      },
    },
    {
      id: "p5",
      name: "Margaret River",
      mode: "light",
      textColor: "#000000",
      colors: ["#63c863"],
      backing: "#e0f6dd",
      speed: 1.2,
      params: {
        width: 17,
        depth: 44,
        height: 9,
        spacing: 1.1,
        clearRadius: 4,
        drift: 1.1,
        opacity: 0.85,
      },
    },
    {
      id: "p6",
      name: "Wombeyan",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#45648f"],
      backing: "#0e1219",
      speed: 1,
      params: {
        width: 19,
        depth: 48,
        height: 12,
        spacing: 1.2,
        clearRadius: 3.5,
        drift: 1,
        opacity: 0.95,
      },
    },
    {
      id: "p7",
      name: "Yarrangobilly",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#336d59"],
      backing: "#0a1411",
      speed: 0.7,
      params: {
        width: 15,
        depth: 40,
        height: 15,
        spacing: 1,
        clearRadius: 3,
        drift: 1.2,
        opacity: 1,
      },
    },
    {
      id: "p8",
      name: "Abercrombie",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#85583f"],
      backing: "#17110c",
      speed: 0.9,
      params: {
        width: 24,
        depth: 58,
        height: 10,
        spacing: 1.7,
        clearRadius: 4.5,
        drift: 0.7,
        opacity: 0.9,
      },
    },
    {
      id: "p9",
      name: "Mole Creek",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#6f52a9"],
      backing: "#15101c",
      speed: 0.6,
      params: {
        width: 20,
        depth: 52,
        height: 13,
        spacing: 1.3,
        clearRadius: 4,
        drift: 0.9,
        opacity: 0.95,
      },
    },
  ],
  "contour-field": [
    {
      id: "p1",
      name: "Dorrigo",
      mode: "light",
      textColor: "#000000",
      colors: ["#62c873"],
      backing: "#ddf6e4",
      speed: 1,
      params: {
        levels: 11,
        hilliness: 0.5,
        scale: 10,
        height: -2,
        clearRadius: 8.5,
        fadeRadius: 60,
        drift: 1,
        opacity: 0.9,
      },
    },
    {
      id: "p2",
      name: "Barrington",
      mode: "light",
      textColor: "#000000",
      colors: ["#72c662"],
      backing: "#e3f5dd",
      speed: 0.7,
      params: {
        levels: 14,
        hilliness: 0.65,
        scale: 8,
        height: -1.8,
        clearRadius: 7,
        fadeRadius: 52,
        drift: 1.2,
        opacity: 0.85,
      },
    },
    {
      id: "p3",
      name: "Monaro",
      mode: "light",
      textColor: "#000000",
      colors: ["#cbb164"],
      backing: "#f5f0dc",
      speed: 0.9,
      params: {
        levels: 8,
        hilliness: 0.4,
        scale: 14,
        height: -2.2,
        clearRadius: 10,
        fadeRadius: 68,
        drift: 0.7,
        opacity: 0.9,
      },
    },
    {
      id: "p4",
      name: "Liverpool Plains",
      mode: "light",
      textColor: "#000000",
      colors: ["#abbb5c"],
      backing: "#edf3da",
      speed: 0.6,
      params: {
        levels: 12,
        hilliness: 0.45,
        scale: 11,
        height: -2.4,
        clearRadius: 9,
        fadeRadius: 64,
        drift: 0.8,
        opacity: 0.95,
      },
    },
    {
      id: "p5",
      name: "Darling Downs",
      mode: "light",
      textColor: "#000000",
      colors: ["#e0a86f"],
      backing: "#f9eee0",
      speed: 1.2,
      params: {
        levels: 10,
        hilliness: 0.55,
        scale: 9,
        height: -2,
        clearRadius: 8,
        fadeRadius: 56,
        drift: 1.1,
        opacity: 0.85,
      },
    },
    {
      id: "p6",
      name: "Breadknife",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#3e6783"],
      backing: "#0d1218",
      speed: 1,
      params: {
        levels: 11,
        hilliness: 0.5,
        scale: 10,
        height: -2,
        clearRadius: 8.5,
        fadeRadius: 60,
        drift: 1,
        opacity: 0.95,
      },
    },
    {
      id: "p7",
      name: "Warrego",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#865740"],
      backing: "#17110c",
      speed: 0.7,
      params: {
        levels: 14,
        hilliness: 0.7,
        scale: 7,
        height: -1.8,
        clearRadius: 7,
        fadeRadius: 50,
        drift: 1.3,
        opacity: 1,
      },
    },
    {
      id: "p8",
      name: "Diamantina",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#326c5e"],
      backing: "#0a1412",
      speed: 0.9,
      params: {
        levels: 8,
        hilliness: 0.4,
        scale: 15,
        height: -2.3,
        clearRadius: 10,
        fadeRadius: 70,
        drift: 0.7,
        opacity: 0.9,
      },
    },
    {
      id: "p9",
      name: "Cooper Creek",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#706134"],
      backing: "#15120b",
      speed: 0.6,
      params: {
        levels: 12,
        hilliness: 0.55,
        scale: 9,
        height: -2.1,
        clearRadius: 9,
        fadeRadius: 58,
        drift: 0.9,
        opacity: 0.95,
      },
    },
  ],
  "drift-slabs": [
    {
      id: "p1",
      name: "Whitehaven",
      mode: "light",
      textColor: "#000000",
      colors: ["#95d7f9", "#6dc9db"],
      backing: "#e3f2fd",
      speed: 1.5,
      params: { count: 13, spread: 3, depth: 13, size: 1, drift: 1 },
    },
    {
      id: "p2",
      name: "Balmoral",
      mode: "light",
      textColor: "#000000",
      colors: ["#a9d3ff", "#9dbbff"],
      backing: "#e5f1ff",
      speed: 1.05,
      params: { count: 10, spread: 2, depth: 15, size: 1.25, drift: 0.7 },
    },
    {
      id: "p3",
      name: "Trigg",
      mode: "light",
      textColor: "#000000",
      colors: ["#84ded6", "#65ceb4"],
      backing: "#dcf5f5",
      speed: 1.35,
      params: { count: 16, spread: 3.5, depth: 12, size: 0.85, drift: 1.3 },
    },
    {
      id: "p4",
      name: "Burleigh",
      mode: "light",
      textColor: "#000000",
      colors: ["#e4cd88", "#e3b471"],
      backing: "#f5f0dc",
      speed: 0.9,
      params: { count: 11, spread: 2.5, depth: 16, size: 1.1, drift: 0.9 },
    },
    {
      id: "p5",
      name: "Sorrento",
      mode: "light",
      textColor: "#000000",
      colors: ["#ffbec7", "#ffa0bd"],
      backing: "#ffebee",
      speed: 1.8,
      params: { count: 14, spread: 3, depth: 13, size: 0.95, drift: 1.1 },
    },
    {
      id: "p6",
      name: "Painted Desert",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#2b3139", "#4e4035"],
      backing: "#0e1219",
      speed: 1.5,
      params: { count: 13, spread: 3, depth: 13, size: 1, drift: 1 },
    },
    {
      id: "p7",
      name: "Ormiston",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#382e2b", "#563b40"],
      backing: "#18100d",
      speed: 1.05,
      params: { count: 10, spread: 2, depth: 15, size: 1.3, drift: 0.7 },
    },
    {
      id: "p8",
      name: "Ellery",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#283234", "#304743"],
      backing: "#0b1316",
      speed: 1.35,
      params: { count: 16, spread: 3.5, depth: 12, size: 0.85, drift: 1.2 },
    },
    {
      id: "p9",
      name: "Karlu Karlu",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#352e3c", "#543a54"],
      backing: "#160f1b",
      speed: 0.9,
      params: { count: 11, spread: 2.5, depth: 14, size: 1.1, drift: 0.9 },
    },
  ],
  "orb-field": [
    {
      id: "p1",
      name: "Moreton",
      mode: "light",
      textColor: "#000000",
      colors: ["#90d9f1", "#68cad3"],
      backing: "#e2f3fb",
      speed: 1.5,
      params: { count: 12, spread: 3, depth: 13, size: 1, drift: 1 },
    },
    {
      id: "p2",
      name: "Stradbroke",
      mode: "light",
      textColor: "#000000",
      colors: ["#e8cc8b", "#ebb075"],
      backing: "#f6f0dd",
      speed: 1.05,
      params: { count: 9, spread: 2, depth: 15, size: 1.3, drift: 0.7 },
    },
    {
      id: "p3",
      name: "Fingal",
      mode: "light",
      textColor: "#000000",
      colors: ["#86e0c2", "#66cf9b"],
      backing: "#ddf5ef",
      speed: 1.35,
      params: { count: 15, spread: 3.5, depth: 12, size: 0.8, drift: 1.3 },
    },
    {
      id: "p4",
      name: "Catseye",
      mode: "light",
      textColor: "#000000",
      colors: ["#a9d3ff", "#a6b9ff"],
      backing: "#e6f1ff",
      speed: 0.9,
      params: { count: 10, spread: 2.5, depth: 16, size: 1.15, drift: 0.85 },
    },
    {
      id: "p5",
      name: "Vivonne",
      mode: "light",
      textColor: "#000000",
      colors: ["#ffbcd1", "#ff9ecb"],
      backing: "#ffebf0",
      speed: 1.8,
      params: { count: 13, spread: 3, depth: 13, size: 0.9, drift: 1.1 },
    },
    {
      id: "p6",
      name: "Wolfe Creek",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#2b3138", "#4c4034"],
      backing: "#0e1219",
      speed: 1.5,
      params: { count: 12, spread: 3, depth: 13, size: 1, drift: 1 },
    },
    {
      id: "p7",
      name: "Henbury",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#382f2b", "#494232"],
      backing: "#18100d",
      speed: 1.05,
      params: { count: 9, spread: 2, depth: 15, size: 1.35, drift: 0.7 },
    },
    {
      id: "p8",
      name: "Tnorala",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#273234", "#30473f"],
      backing: "#0b1315",
      speed: 1.35,
      params: { count: 15, spread: 3.5, depth: 12, size: 0.8, drift: 1.25 },
    },
    {
      id: "p9",
      name: "Gosses Bluff",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#342e3c", "#513b55"],
      backing: "#15101b",
      speed: 0.9,
      params: { count: 10, spread: 2.5, depth: 14, size: 1.15, drift: 0.85 },
    },
  ],
  "halo-rings": [
    {
      id: "p1",
      name: "Wave Rock",
      mode: "light",
      textColor: "#000000",
      colors: ["#eacb8c", "#ebb075"],
      backing: "#f6f0de",
      speed: 1.5,
      params: { count: 5, spread: 3, depth: 13, size: 1, tube: 0.16, drift: 1 },
    },
    {
      id: "p2",
      name: "Remarkables",
      mode: "light",
      textColor: "#000000",
      colors: ["#9cd5ff", "#71c7e4"],
      backing: "#e4f2fe",
      speed: 1.05,
      params: { count: 4, spread: 2, depth: 15, size: 1.25, tube: 0.22, drift: 0.7 },
    },
    {
      id: "p3",
      name: "Pinnacles",
      mode: "light",
      textColor: "#000000",
      colors: ["#e1ce86", "#c3c060"],
      backing: "#f4f0dc",
      speed: 1.35,
      params: { count: 6, spread: 3.5, depth: 12, size: 0.85, tube: 0.12, drift: 1.3 },
    },
    {
      id: "p4",
      name: "Sawtell",
      mode: "light",
      textColor: "#000000",
      colors: ["#8cdbea", "#64cbcb"],
      backing: "#e0f3f9",
      speed: 0.9,
      params: { count: 5, spread: 2.5, depth: 15, size: 1.1, tube: 0.18, drift: 0.9 },
    },
    {
      id: "p5",
      name: "Currarong",
      mode: "light",
      textColor: "#000000",
      colors: ["#b2d0ff", "#aab8ff"],
      backing: "#e8f0ff",
      speed: 1.8,
      params: { count: 5, spread: 3, depth: 13, size: 0.95, tube: 0.14, drift: 1.1 },
    },
    {
      id: "p6",
      name: "Devils Marbles",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#2b3139", "#4d4035"],
      backing: "#0e1219",
      speed: 1.5,
      params: { count: 5, spread: 3, depth: 13, size: 1, tube: 0.16, drift: 1 },
    },
    {
      id: "p7",
      name: "Bungle Bungle",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#372f2a", "#494232"],
      backing: "#17110d",
      speed: 1.05,
      params: { count: 4, spread: 2, depth: 15, size: 1.3, tube: 0.24, drift: 0.7 },
    },
    {
      id: "p8",
      name: "Kings Canyon",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#392e2c", "#4c4034"],
      backing: "#19100e",
      speed: 1.35,
      params: { count: 6, spread: 3.5, depth: 12, size: 0.85, tube: 0.12, drift: 1.25 },
    },
    {
      id: "p9",
      name: "Standley",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#332e3c", "#503b55"],
      backing: "#15101c",
      speed: 0.9,
      params: { count: 5, spread: 2.5, depth: 14, size: 1.05, tube: 0.18, drift: 0.9 },
    },
  ],
  "skyline-prisms": [
    {
      id: "p1",
      name: "Apostles",
      mode: "light",
      textColor: "#000000",
      colors: ["#9cd5ff", "#71c7e4"],
      backing: "#e4f2fe",
      speed: 1.5,
      params: { count: 20, depth: 14, tallest: 8, drift: 1 },
    },
    {
      id: "p2",
      name: "Organ Pipes",
      mode: "light",
      textColor: "#000000",
      colors: ["#b9cfff", "#83c1ff"],
      backing: "#eaf0ff",
      speed: 1.05,
      params: { count: 24, depth: 16, tallest: 10, drift: 0.7 },
    },
    {
      id: "p3",
      name: "Cathedral Range",
      mode: "light",
      textColor: "#000000",
      colors: ["#86e0c2", "#66cf9b"],
      backing: "#ddf5ef",
      speed: 1.35,
      params: { count: 16, depth: 12, tallest: 6, drift: 1.3 },
    },
    {
      id: "p4",
      name: "Glasshouse",
      mode: "light",
      textColor: "#000000",
      colors: ["#87e2a5", "#67d179"],
      backing: "#ddf6e7",
      speed: 0.9,
      params: { count: 22, depth: 15, tallest: 9, drift: 0.85 },
    },
    {
      id: "p5",
      name: "Hazards",
      mode: "light",
      textColor: "#000000",
      colors: ["#ffbfb7", "#ffa2a9"],
      backing: "#ffece8",
      speed: 1.8,
      params: { count: 18, depth: 13, tallest: 7, drift: 1.1 },
    },
    {
      id: "p6",
      name: "Three Sisters",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#2b3139", "#4c4034"],
      backing: "#0e1219",
      speed: 1.5,
      params: { count: 20, depth: 14, tallest: 8, drift: 1 },
    },
    {
      id: "p7",
      name: "Balls Pyramid",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#293236", "#304745"],
      backing: "#0c1317",
      speed: 1.05,
      params: { count: 16, depth: 12, tallest: 10, drift: 1.2 },
    },
    {
      id: "p8",
      name: "Frenchmans Cap",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#312f3d", "#4c3c57"],
      backing: "#13101c",
      speed: 1.35,
      params: { count: 24, depth: 16, tallest: 6, drift: 0.7 },
    },
    {
      id: "p9",
      name: "Federation Peak",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#273331", "#31473a"],
      backing: "#0a1413",
      speed: 0.9,
      params: { count: 18, depth: 13, tallest: 9, drift: 0.9 },
    },
  ],
  "point-swell": [
    {
      id: "p1",
      name: "Bondi",
      mode: "light",
      textColor: "#000000",
      colors: ["#76c5ed", "#5bbbce"],
      backing: "#e3f2fc",
      speed: 0.4,
      params: {
        spacing: 0.9,
        amplitude: 0.45,
        wavelength: 9,
        clearRadius: 4,
        fadeRadius: 40,
        pointSize: 0.08,
        drift: 1,
        opacity: 0.9,
      },
    },
    {
      id: "p2",
      name: "Snapper",
      mode: "light",
      textColor: "#000000",
      colors: ["#64cbcb", "#54bfad"],
      backing: "#ddf4f6",
      speed: 0.35,
      params: {
        spacing: 1.2,
        amplitude: 0.6,
        wavelength: 12,
        clearRadius: 5,
        fadeRadius: 46,
        pointSize: 0.1,
        drift: 0.8,
        opacity: 0.85,
      },
    },
    {
      id: "p3",
      name: "Bells",
      mode: "light",
      textColor: "#000000",
      colors: ["#93beff", "#69b5eb"],
      backing: "#e8f0ff",
      speed: 0.45,
      params: {
        spacing: 0.7,
        amplitude: 0.35,
        wavelength: 7,
        clearRadius: 3.5,
        fadeRadius: 36,
        pointSize: 0.06,
        drift: 1.3,
        opacity: 0.9,
      },
    },
    {
      id: "p4",
      name: "Crescent",
      mode: "light",
      textColor: "#000000",
      colors: ["#d4ba69", "#d6a55f"],
      backing: "#f5f0dc",
      speed: 0.3,
      params: {
        spacing: 1,
        amplitude: 0.5,
        wavelength: 10,
        clearRadius: 4.5,
        fadeRadius: 42,
        pointSize: 0.09,
        drift: 0.9,
        opacity: 0.95,
      },
    },
    {
      id: "p5",
      name: "Merimbula",
      mode: "light",
      textColor: "#000000",
      colors: ["#65ceb4", "#55c194"],
      backing: "#ddf5f0",
      speed: 0.5,
      params: {
        spacing: 0.8,
        amplitude: 0.4,
        wavelength: 8,
        clearRadius: 4,
        fadeRadius: 38,
        pointSize: 0.07,
        drift: 1.1,
        opacity: 0.85,
      },
    },
    {
      id: "p6",
      name: "Shipstern",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#42607e", "#855838"],
      backing: "#0e1219",
      speed: 0.4,
      params: {
        spacing: 0.9,
        amplitude: 0.45,
        wavelength: 9,
        clearRadius: 4,
        fadeRadius: 40,
        pointSize: 0.08,
        drift: 1,
        opacity: 0.95,
      },
    },
    {
      id: "p7",
      name: "Gunnamatta",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#38646c", "#2d6d62"],
      backing: "#0b1315",
      speed: 0.35,
      params: {
        spacing: 1.1,
        amplitude: 0.65,
        wavelength: 12,
        clearRadius: 5,
        fadeRadius: 46,
        pointSize: 0.1,
        drift: 0.8,
        opacity: 1,
      },
    },
    {
      id: "p8",
      name: "Cactus",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#356656", "#72612f"],
      backing: "#0a1411",
      speed: 0.45,
      params: {
        spacing: 0.7,
        amplitude: 0.35,
        wavelength: 7,
        clearRadius: 3.5,
        fadeRadius: 36,
        pointSize: 0.06,
        drift: 1.25,
        opacity: 0.9,
      },
    },
    {
      id: "p9",
      name: "Winkipop",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#685197", "#8a46a1"],
      backing: "#14101c",
      speed: 0.3,
      params: {
        spacing: 1,
        amplitude: 0.5,
        wavelength: 10,
        clearRadius: 4.5,
        fadeRadius: 42,
        pointSize: 0.09,
        drift: 0.9,
        opacity: 0.95,
      },
    },
  ],
  "dust-drift": [
    {
      id: "p1",
      name: "Mallee",
      mode: "light",
      textColor: "#000000",
      colors: ["#d4ba69", "#d6a55f"],
      backing: "#f5f0dc",
      speed: 0.4,
      params: {
        count: 900,
        innerRadius: 10,
        outerRadius: 26,
        twinkle: 0.6,
        pointSize: 0.09,
        drift: 1,
        opacity: 0.9,
      },
    },
    {
      id: "p2",
      name: "Mulga",
      mode: "light",
      textColor: "#000000",
      colors: ["#ebb075", "#f0986c"],
      backing: "#f9eee0",
      speed: 0.35,
      params: {
        count: 650,
        innerRadius: 12,
        outerRadius: 30,
        twinkle: 0.45,
        pointSize: 0.09,
        drift: 0.7,
        opacity: 0.85,
      },
    },
    {
      id: "p3",
      name: "Saltbush",
      mode: "light",
      textColor: "#000000",
      colors: ["#66cf9b", "#56c27a"],
      backing: "#ddf6eb",
      speed: 0.45,
      params: {
        count: 1200,
        innerRadius: 9,
        outerRadius: 24,
        twinkle: 0.75,
        pointSize: 0.08,
        drift: 1.3,
        opacity: 0.9,
      },
    },
    {
      id: "p4",
      name: "Brigalow",
      mode: "light",
      textColor: "#000000",
      colors: ["#68d268", "#67c255"],
      backing: "#def6df",
      speed: 0.3,
      params: {
        count: 800,
        innerRadius: 11,
        outerRadius: 28,
        twinkle: 0.55,
        pointSize: 0.09,
        drift: 0.85,
        opacity: 0.95,
      },
    },
    {
      id: "p5",
      name: "Bluebush",
      mode: "light",
      textColor: "#000000",
      colors: ["#7bc3f7", "#5fb9d7"],
      backing: "#e4f2fe",
      speed: 0.5,
      params: {
        count: 1000,
        innerRadius: 10,
        outerRadius: 26,
        twinkle: 0.65,
        pointSize: 0.09,
        drift: 1.1,
        opacity: 0.85,
      },
    },
    {
      id: "p6",
      name: "Coalsack",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#496489", "#72612f"],
      backing: "#0e1219",
      speed: 0.4,
      params: {
        count: 900,
        innerRadius: 10,
        outerRadius: 26,
        twinkle: 0.6,
        pointSize: 0.09,
        drift: 1,
        opacity: 0.95,
      },
    },
    {
      id: "p7",
      name: "Magellanic",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#3e6876", "#2c6c67"],
      backing: "#0c1316",
      speed: 0.35,
      params: {
        count: 1300,
        innerRadius: 9,
        outerRadius: 24,
        twinkle: 0.8,
        pointSize: 0.08,
        drift: 1.2,
        opacity: 1,
      },
    },
    {
      id: "p8",
      name: "Emu Sky",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#825945", "#765f31"],
      backing: "#17110d",
      speed: 0.45,
      params: {
        count: 650,
        innerRadius: 12,
        outerRadius: 32,
        twinkle: 0.5,
        pointSize: 0.09,
        drift: 0.7,
        opacity: 0.9,
      },
    },
    {
      id: "p9",
      name: "Parkes",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#72549c", "#8e449d"],
      backing: "#15101b",
      speed: 0.3,
      params: {
        count: 1050,
        innerRadius: 10,
        outerRadius: 28,
        twinkle: 0.7,
        pointSize: 0.09,
        drift: 0.9,
        opacity: 0.95,
      },
    },
  ],
};

/** The anchor preset backing a 3D look's Theme tile and live-derived colours: `p1` for light themes, `p6` for dark (the shader-pack convention). */
export function scene3dThemeAnchor(
  look: string,
  theme: Theme,
): Scene3dBackgroundPreset | undefined {
  const mode = theme.mode ?? "dark";
  return SCENE3D_BACKGROUND_PRESETS[look]?.find((p) => p.id === (mode === "light" ? "p1" : "p6"));
}
