import type { Scene3dBackgroundDef, Scene3dBackgroundPreset } from "../../types";
import { LongExposure } from "./LongExposure";

/** Long exposure (kinetic): southern circumpolar star trails turning clockwise round an off-stage pole, the Southern Cross and the Pointers rising out of the upper right, over a still sea that mirrors them, low headlands at 25 to 60 units and a lighthouse. The sea and coast are world space, so a camera move glides over the water toward the coast while the stars hold still. Cards use the ceiling pose: trails fill the tile over a band of coast. */
export const look: Scene3dBackgroundDef = {
  id: "long-exposure",
  name: "Long exposure",
  family: "kinetic",
  previewCamera: "ceiling",
  colorSlots: [
    { label: "Trail", fallback: "#535d76" },
    { label: "Bright star", fallback: "#8893a9", glow: true },
    { label: "Horizon", fallback: "#3a302a" },
  ],
  params: {
    poleAzimuth: { label: "Pole azimuth", default: 55, min: -90, max: 90, step: 1 },
    poleHeight: { label: "Pole height", default: 30, min: 24, max: 45, step: 0.5 },
    trailLength: { label: "Exposure", default: 38, min: 10, max: 60, step: 1 },
    density: { label: "Star density", default: 0.45, min: 0.2, max: 1, step: 0.01 },
    turn: { label: "Sky turn", default: 1, min: 0, max: 3, step: 0.05 },
    horizon: { label: "Horizon glow", default: 0.6, min: 0, max: 1, step: 0.01 },
    skyHour: { label: "Sky hour", default: 0, min: 0, max: 24, step: 0.25 },
    coast: { label: "Coastline", default: 1, min: 1, max: 4, step: 1 },
    headlands: { label: "Headlands", default: 1, min: 0, max: 1.5, step: 0.05 },
    mist: { label: "Sea mist", default: 0.5, min: 0, max: 1, step: 0.01 },
    swell: { label: "Swell", default: 0.5, min: 0, max: 1, step: 0.01 },
    lamp: { label: "Lighthouse", default: 0.8, min: 0, max: 1, step: 0.01 },
  },
  Component: LongExposure,
};

type Tune = Omit<Scene3dBackgroundPreset, "mode" | "textColor">;

const preset = (mode: "light" | "dark", p: Tune): Scene3dBackgroundPreset => ({
  ...p,
  mode,
  textColor: mode === "light" ? "#000000" : "#ffffff",
});

/** Australian capes and lighthouses. p1 and p6 are the approved sketch palettes (p1's trail lifted to the Theme tile floor). Light presets print as fine engraved arcs; dark ones as a night exposure. */
export const presets: Scene3dBackgroundPreset[] = [
  preset("light", {
    id: "p1",
    name: "Cape Byron",
    colors: ["#929bab", "#b3955f", "#e6d6c2"],
    backing: "#f3f5f9",
    speed: 1,
    params: {
      poleAzimuth: 55,
      poleHeight: 30,
      trailLength: 38,
      density: 0.45,
      turn: 1,
      horizon: 0.6,
      skyHour: 0,
      coast: 1,
      headlands: 1,
      mist: 0.5,
      swell: 0.5,
      lamp: 0.8,
    },
  }),
  preset("light", {
    id: "p2",
    name: "Smoky Cape",
    colors: ["#93a39b", "#b8976a", "#e2dccd"],
    backing: "#f2f4ef",
    speed: 1,
    params: {
      poleAzimuth: 30,
      poleHeight: 36,
      trailLength: 50,
      density: 0.38,
      turn: 0.9,
      horizon: 0.4,
      skyHour: 6,
      coast: 4,
      headlands: 1.1,
      mist: 0.85,
      swell: 0.3,
      lamp: 0.7,
    },
  }),
  preset("light", {
    id: "p3",
    name: "Sugarloaf Point",
    colors: ["#a59683", "#ba916a", "#ecd5bf"],
    backing: "#f7f2eb",
    speed: 1,
    params: {
      poleAzimuth: 70,
      poleHeight: 26,
      trailLength: 28,
      density: 0.6,
      turn: 1.2,
      horizon: 0.75,
      skyHour: 14,
      coast: 1,
      headlands: 0.8,
      mist: 0.35,
      swell: 0.7,
      lamp: 0.9,
    },
  }),
  preset("light", {
    id: "p4",
    name: "Point Perpendicular",
    colors: ["#8f9fb6", "#bf9a6b", "#dce2ea"],
    backing: "#f1f4f9",
    speed: 1,
    params: {
      poleAzimuth: -50,
      poleHeight: 32,
      trailLength: 44,
      density: 0.5,
      turn: 1,
      horizon: 0.5,
      skyHour: 3,
      coast: 3,
      headlands: 1.3,
      mist: 0.3,
      swell: 0.55,
      lamp: 0.75,
    },
  }),
  preset("light", {
    id: "p5",
    name: "Green Cape",
    colors: ["#97a5a0", "#c0a274", "#e6dccb"],
    backing: "#f4f4ef",
    speed: 1,
    params: {
      poleAzimuth: -35,
      poleHeight: 40,
      trailLength: 60,
      density: 0.3,
      turn: 0.8,
      horizon: 0.55,
      skyHour: 20,
      coast: 2,
      headlands: 0.6,
      mist: 0.6,
      swell: 0.85,
      lamp: 0.6,
    },
  }),
  preset("dark", {
    id: "p6",
    name: "Maatsuyker",
    colors: ["#535d76", "#8893a9", "#3a302a"],
    backing: "#0c101a",
    speed: 1,
    params: {
      poleAzimuth: 55,
      poleHeight: 30,
      trailLength: 38,
      density: 0.45,
      turn: 1,
      horizon: 0.6,
      skyHour: 0,
      coast: 1,
      headlands: 1,
      mist: 0.5,
      swell: 0.5,
      lamp: 0.8,
    },
  }),
  preset("dark", {
    id: "p7",
    name: "Tasman Island",
    colors: ["#4a6670", "#80969c", "#392f25"],
    backing: "#0a1214",
    speed: 1,
    params: {
      poleAzimuth: 28,
      poleHeight: 38,
      trailLength: 50,
      density: 0.55,
      turn: 1.1,
      horizon: 0.5,
      skyHour: 8,
      coast: 4,
      headlands: 1.4,
      mist: 0.4,
      swell: 0.4,
      lamp: 0.85,
    },
  }),
  preset("dark", {
    id: "p8",
    name: "Cape Wickham",
    colors: ["#5d5873", "#9a87a1", "#48322a"],
    backing: "#100d16",
    speed: 1,
    params: {
      poleAzimuth: -55,
      poleHeight: 28,
      trailLength: 30,
      density: 0.6,
      turn: 1.3,
      horizon: 0.8,
      skyHour: 16,
      coast: 2,
      headlands: 0.7,
      mist: 0.65,
      swell: 0.6,
      lamp: 1,
    },
  }),
  preset("dark", {
    id: "p9",
    name: "Cape du Couedic",
    colors: ["#67604f", "#a28c68", "#3a2b22"],
    backing: "#0f0e0b",
    speed: 1,
    params: {
      poleAzimuth: -72,
      poleHeight: 42,
      trailLength: 58,
      density: 0.35,
      turn: 0.7,
      horizon: 0.4,
      skyHour: 21,
      coast: 3,
      headlands: 1.2,
      mist: 0.25,
      swell: 0.75,
      lamp: 0.7,
    },
  }),
];
