import { TEXT_CALM_PARAM } from "../../kit/stage";
import type { Scene3dBackgroundDef, Scene3dBackgroundPreset } from "../../types";
import { RainCanopy, SPACING_MIN } from "./RainCanopy";

export const look: Scene3dBackgroundDef = {
  id: "rain-canopy",
  name: "Rain canopy",
  family: "kinetic",
  colorSlots: [
    { label: "Drop", fallback: "#5c4838" },
    { label: "Thread", fallback: "#2c2825" },
    { label: "Crest", fallback: "#6d5843" },
  ],
  params: {
    amplitude: { label: "Swell", default: 0.9, min: 0, max: 1.6, step: 0.05 },
    height: { label: "Canopy height", default: 5.8, min: 4, max: 8, step: 0.1 },
    spacing: { label: "Drop spacing", default: 1.2, min: SPACING_MIN, max: 2, step: 0.05 },
    droop: { label: "Bell droop", default: 3.6, min: 0, max: 4.6, step: 0.1 },
    period: { label: "Loop length (s)", default: 90, min: 45, max: 240, step: 5 },
    threads: { label: "Thread opacity", default: 0.25, min: 0, max: 0.5, step: 0.01 },
    textCalm: TEXT_CALM_PARAM,
  },
  Component: RainCanopy,
};

const light = { mode: "light", textColor: "#000000" } as const;
const dark = { mode: "dark", textColor: "#ffffff" } as const;

export const presets: Scene3dBackgroundPreset[] = [
  {
    id: "p1",
    name: "Boronia",
    ...light,
    colors: ["#b39379", "#d4cbbf", "#e6cdb0"],
    backing: "#f6f1ea",
    speed: 1,
    params: {
      amplitude: 0.9,
      height: 5.8,
      spacing: 1.2,
      droop: 3.6,
      period: 90,
      threads: 0.25,
      textCalm: 0.6,
    },
  },
  {
    id: "p2",
    name: "Flannel Flower",
    ...light,
    colors: ["#959c89", "#cbd0c1", "#e0e4d3"],
    backing: "#f5f6ef",
    speed: 0.9,
    params: {
      amplitude: 0.6,
      height: 6.6,
      spacing: 1.5,
      droop: 3,
      period: 120,
      threads: 0.2,
      textCalm: 0.7,
    },
  },
  {
    id: "p3",
    name: "Waxflower",
    ...light,
    colors: ["#b1919d", "#d6c8ce", "#e9d4da"],
    backing: "#f8f2f4",
    speed: 1,
    params: {
      amplitude: 1.1,
      height: 5.4,
      spacing: 1,
      droop: 4,
      period: 75,
      threads: 0.3,
      textCalm: 0.6,
    },
  },
  {
    id: "p4",
    name: "Fan Flower",
    ...light,
    colors: ["#9399b5", "#cacdda", "#dadaee"],
    backing: "#f4f4f9",
    speed: 0.8,
    params: {
      amplitude: 0.5,
      height: 6.2,
      spacing: 1.3,
      droop: 2.2,
      period: 150,
      threads: 0.15,
      textCalm: 0.8,
    },
  },
  {
    id: "p5",
    name: "Billy Buttons",
    ...light,
    colors: ["#b69557", "#dacbad", "#edd59c"],
    backing: "#fbf5e6",
    speed: 1.2,
    params: {
      amplitude: 1.3,
      height: 6,
      spacing: 1.7,
      droop: 3.2,
      period: 60,
      threads: 0.35,
      textCalm: 0.5,
    },
  },
  {
    id: "p6",
    name: "Blackwood",
    ...dark,
    colors: ["#5c4838", "#2c2825", "#6d5843"],
    backing: "#120f0d",
    speed: 1,
    params: {
      amplitude: 0.9,
      height: 5.8,
      spacing: 1.2,
      droop: 3.6,
      period: 90,
      threads: 0.25,
      textCalm: 0.6,
    },
  },
  {
    id: "p7",
    name: "Huon Pine",
    ...dark,
    colors: ["#5e5230", "#2a2718", "#6c5f36"],
    backing: "#13120b",
    speed: 0.9,
    params: {
      amplitude: 0.7,
      height: 6.8,
      spacing: 1,
      droop: 4.2,
      period: 110,
      threads: 0.3,
      textCalm: 0.6,
    },
  },
  {
    id: "p8",
    name: "Marri",
    ...dark,
    colors: ["#633d36", "#2e2220", "#7a4c41"],
    backing: "#140d0c",
    speed: 1.1,
    params: {
      amplitude: 1.2,
      height: 5.5,
      spacing: 1.4,
      droop: 3,
      period: 70,
      threads: 0.2,
      textCalm: 0.5,
    },
  },
  {
    id: "p9",
    name: "Myrtle Beech",
    ...dark,
    colors: ["#3b5448", "#1f2a25", "#4a6656"],
    backing: "#0c1210",
    speed: 0.8,
    params: {
      amplitude: 0.8,
      height: 6.4,
      spacing: 1.8,
      droop: 2.6,
      period: 180,
      threads: 0.4,
      textCalm: 0.7,
    },
  },
];
