import { TEXT_CALM_PARAM } from "../../kit";
import type {
  Scene3dBackgroundDef,
  Scene3dBackgroundPreset,
  Scene3dCompanionLighting,
} from "../../types";
import { RISO_SUN_AZIMUTH, RISO_SUN_ELEVATION_DEG } from "./model";
import { RisoDunes } from "./RisoDunes";

export const look: Scene3dBackgroundDef = {
  id: "riso-dunes",
  name: "Riso dunes",
  family: "atmosphere",
  colorSlots: [
    { label: "Key ink", fallback: "#6f603c" },
    { label: "Tint ink", fallback: "#6d3f34" },
    { label: "Paper", fallback: "#121f25" },
  ],
  params: {
    clearRadius: { label: "Clearing", default: 8, min: 5, max: 16, step: 0.5 },
    inkReach: { label: "Ink reach", default: 15, min: 10, max: 30, step: 0.5 },
    duneHeight: { label: "Dune height", default: 1.3, min: 0.3, max: 3, step: 0.05 },
    duneSpacing: { label: "Dune spacing", default: 17, min: 8, max: 28, step: 0.5 },
    misregister: { label: "Misregistration", default: 0.1, min: 0, max: 0.3, step: 0.01 },
    grain: { label: "Grain", default: 0.5, min: 0, max: 1, step: 0.05 },
    drift: { label: "Dune drift", default: 0.05, min: 0, max: 0.2, step: 0.005 },
    sunSwing: { label: "Sun swing", default: 20, min: 0, max: 45, step: 1 },
    textCalm: TEXT_CALM_PARAM,
  },
  Component: RisoDunes,
};

/** The companion rig follows the painted sun's centre: low and warm, behind the stage for light stock, on the camera side for dark. */
const sun = (
  mode: "light" | "dark",
  intensity: number,
  kelvin: number,
): Scene3dCompanionLighting => ({
  sun: {
    azimuthDeg: mode === "light" ? RISO_SUN_AZIMUTH.light - 360 : RISO_SUN_AZIMUTH.dark,
    elevationDeg: RISO_SUN_ELEVATION_DEG,
    intensity,
    kelvin,
  },
});

export const presets: Scene3dBackgroundPreset[] = [
  {
    id: "p1",
    name: "Rainbow Beach",
    mode: "light",
    textColor: "#000000",
    colors: ["#65a2ad", "#d9a89b", "#f8f4eb"],
    backing: "#ede7da",
    speed: 1,
    params: {
      clearRadius: 8,
      inkReach: 15,
      duneHeight: 1.3,
      duneSpacing: 17,
      misregister: 0.1,
      grain: 0.5,
      drift: 0.05,
      sunSwing: 20,
      textCalm: 0.6,
    },
    lighting: sun("light", 2, 3600),
  },
  {
    id: "p2",
    name: "Carlo Sandblow",
    mode: "light",
    textColor: "#000000",
    colors: ["#8497c0", "#e3c88c", "#f7f2e6"],
    backing: "#ebe4d3",
    speed: 1,
    params: {
      clearRadius: 9,
      inkReach: 16,
      duneHeight: 1.3,
      duneSpacing: 20,
      misregister: 0.06,
      grain: 0.35,
      drift: 0.04,
      sunSwing: 16,
      textCalm: 0.6,
    },
    lighting: sun("light", 1.8, 4200),
  },
  {
    id: "p3",
    name: "Teewah",
    mode: "light",
    textColor: "#000000",
    colors: ["#c9867a", "#e0bf78", "#f8f1e4"],
    backing: "#efe3cf",
    speed: 0.9,
    params: {
      clearRadius: 7.5,
      inkReach: 14,
      duneHeight: 0.9,
      duneSpacing: 11,
      misregister: 0.2,
      grain: 0.75,
      drift: 0.06,
      sunSwing: 28,
      textCalm: 0.65,
    },
    lighting: sun("light", 2.2, 3200),
  },
  {
    id: "p4",
    name: "Tangalooma",
    mode: "light",
    textColor: "#000000",
    colors: ["#70a390", "#e5b7ae", "#f5f3ee"],
    backing: "#e6e6df",
    speed: 1.1,
    params: {
      clearRadius: 10,
      inkReach: 17,
      duneHeight: 1.3,
      duneSpacing: 19,
      misregister: 0.12,
      grain: 0.55,
      drift: 0.07,
      sunSwing: 24,
      textCalm: 0.6,
    },
    lighting: sun("light", 2, 3800),
  },
  {
    id: "p5",
    name: "Lake Wabby",
    mode: "light",
    textColor: "#000000",
    colors: ["#8d9e6b", "#a8cfca", "#f4f1e6"],
    backing: "#e5e6d8",
    speed: 0.9,
    params: {
      clearRadius: 8.5,
      inkReach: 14.5,
      duneHeight: 1,
      duneSpacing: 13,
      misregister: 0.08,
      grain: 0.4,
      drift: 0.045,
      sunSwing: 12,
      textCalm: 0.75,
    },
    lighting: sun("light", 1.6, 4600),
  },
  {
    id: "p6",
    name: "Big Red",
    mode: "dark",
    textColor: "#ffffff",
    colors: ["#6f603c", "#6d3f34", "#121f25"],
    backing: "#11171f",
    speed: 1,
    params: {
      clearRadius: 8,
      inkReach: 15,
      duneHeight: 1.3,
      duneSpacing: 17,
      misregister: 0.1,
      grain: 0.5,
      drift: 0.05,
      sunSwing: 20,
      textCalm: 0.6,
    },
    lighting: sun("dark", 1.6, 3000),
  },
  {
    id: "p7",
    name: "Cape Flattery",
    mode: "dark",
    textColor: "#ffffff",
    colors: ["#4f6275", "#2f5a5c", "#0f1a22"],
    backing: "#0c141b",
    speed: 1,
    params: {
      clearRadius: 8,
      inkReach: 16,
      duneHeight: 1.3,
      duneSpacing: 18,
      misregister: 0.14,
      grain: 0.7,
      drift: 0.055,
      sunSwing: 30,
      textCalm: 0.6,
    },
    lighting: sun("dark", 1.4, 5200),
  },
  {
    id: "p8",
    name: "Hinchinbrook",
    mode: "dark",
    textColor: "#ffffff",
    colors: ["#546740", "#5c3b4d", "#141a17"],
    backing: "#0f1412",
    speed: 0.9,
    params: {
      clearRadius: 9.5,
      inkReach: 18,
      duneHeight: 1.3,
      duneSpacing: 22,
      misregister: 0.07,
      grain: 0.45,
      drift: 0.04,
      sunSwing: 14,
      textCalm: 0.65,
    },
    lighting: sun("dark", 1.5, 3400),
  },
  {
    id: "p9",
    name: "Shoalwater",
    mode: "dark",
    textColor: "#ffffff",
    colors: ["#4c6189", "#6d4536", "#10151f"],
    backing: "#0e131c",
    speed: 1.1,
    params: {
      clearRadius: 7,
      inkReach: 13,
      duneHeight: 1,
      duneSpacing: 12,
      misregister: 0.18,
      grain: 0.6,
      drift: 0.08,
      sunSwing: 22,
      textCalm: 0.6,
    },
    lighting: sun("dark", 1.7, 2800),
  },
];
