export { lookSeconds, loopSeconds } from "./clock";
export {
  COMPANION_ID_PREFIX,
  COMPANION_MAX_LIGHTS,
  companionLightingProblem,
  stageSpot,
} from "./companion";
export {
  createDishDiscGeometry,
  DISH_FLOOR_VERTEX_SHADER,
  type DishShape,
  dishHeight,
  dishSlope,
  LOOK_GLSL_DISH,
} from "./dish";
export {
  glslFloat,
  LOOK_GLSL_AA,
  LOOK_GLSL_BACKING,
  LOOK_GLSL_FRAGMENT,
  LOOK_GLSL_FRAME,
  LOOK_GLSL_HASH,
  LOOK_GLSL_NOISE,
  LOOK_GLSL_STAGE,
  LOOK_GLSL_VERTEX,
  LOOK_GLSL_VERTEX_HELPERS,
  LOOK_VERTEX_SHADER,
} from "./glsl";
export {
  GOBO_PENUMBRA,
  type GoboHit,
  type GoboSunPath,
  goboCompanionSun,
  goboPenumbra,
  goboSunAzimuth,
  goboSunDirection,
  LOOK_GLSL_GOBO,
  traceGoboCylinder,
  traceGoboPlane,
  writeGoboSun,
} from "./gobo";
export {
  useInstancedLayout,
  useLookMaterial,
  useLookMaterials,
  useLookTime,
  useSeededPlacements,
  useStaticInstancedLayout,
} from "./hooks";
export {
  INK_EDGE_PAD_PX,
  INK_MIN_PX,
  INK_RASTER_FLOOR_PX,
  INK_RIBBON_FRAGMENT,
  type InkParam,
  type InkRibbonSpec,
  type InkSegments,
  type InkStrand,
  inkLoop,
  inkPolyline,
  inkRasterSync,
  inkRibbonGeometry,
  inkRibbonMaterial,
  inkRibbonSegments,
  inkRibbonVertexShader,
  inkStrands,
  showInkStrands,
  useInkRibbonGeometry,
} from "./inkRibbon";
export {
  createInstanceScratch,
  hexLattice,
  type InstancePose,
  type InstanceScratch,
  type LatticePoint,
  LOOK_GLSL_INSTANCE_ANCHOR,
  seededPlacements,
  writeInstanceColors,
  writeInstanceMatrices,
  writeStaticInstances,
} from "./instanced";
export {
  createLookMaterial,
  type LookMaterialSpec,
  lookColor,
  lookColorUniform,
  lookLuminance,
  lookMaterialProblem,
  syncLookFrame,
} from "./material";
export { fract, smoothstep } from "./math";
export {
  LOOK_GLSL_MEDALLION,
  MEDALLION_MIN_HALF_PX,
  medallionLine,
  medallionTurn,
} from "./medallion";
export {
  LOOK_GLSL_PRINT,
  PRINT_SLIP_ANGLE_DEG,
  printBayer,
  printDotRadius,
  printPlateSlip,
  printR2,
} from "./printScreen";
export {
  createRingBandsGeometry,
  createRingBandUniforms,
  LOOK_GLSL_RING_BANDS,
  LOOK_GLSL_RING_EDGE,
  LOOK_GLSL_RING_VERTEX,
  RING_BANDS_MAX,
  RING_BANDS_VERTEX_SHADER,
  type RingBandShape,
  type RingBandsGeometryOptions,
  type RingFloorShape,
  ringBandAngle,
  ringBandDrawOrder,
} from "./ringBands";
export {
  LOOK_GLSL_SKY,
  SKY_DOME_CAMERA_FAR,
  SKY_DOME_CAMERA_REACH,
  SKY_DOME_RADIUS,
  SKY_DOME_VERTEX_SHADER,
  skyDomeMaterial,
  skyDomeRadius,
  useSkyDomeGeometry,
} from "./skyDome";
export {
  LOOK_REFERENCE_HEIGHT,
  STAGE_FADE_WINDOW,
} from "./stage";
export {
  BRUSH_ATLAS,
  BRUSH_SHAPES,
  type BrushMaskLevel,
  brushMaskMips,
  brushMaskPixels,
  brushMaskTexture,
  brushMaskUniforms,
  createStrokeSplatGeometry,
  orderSplatsFarToNear,
  packStrokeSplats,
  STROKE_SPLAT_GLSL_FRAGMENT,
  STROKE_SPLAT_GLSL_VERTEX,
  STROKE_SPLAT_MATERIAL,
  type StrokeSplat,
  splatBoilStep,
  useSplatBoilStep,
  useStrokeSplatGeometry,
} from "./strokeSplats";
export {
  createTinyTexture,
  decodeTinyBytes,
  getPaperGrainTexture,
  PAPER_GRAIN_SIZE,
  paperGrainImage,
  periodicNoise,
  type TinyImage,
  type TinyMip,
  tinyHash,
  tinyMipChain,
  tinyTexture,
} from "./tinyTextures";
