import type { Scene3dBackgroundDef, Scene3dBackgroundPreset } from "../../types";
import { WashDome } from "./WashDome";

export const look: Scene3dBackgroundDef = {
  id: "wash-dome",
  name: "Wash dome",
  family: "painted",
  colorSlots: [
    { label: "Wash", fallback: "#30355a" },
    { label: "Pool edge", fallback: "#141527" },
    { label: "Bloom", fallback: "#785a50" },
  ],
  params: {
    coverage: { label: "Coverage", default: 0.35, min: 0.1, max: 0.6, step: 0.01 },
    calmHeight: { label: "Calm horizon", default: 9, min: 0, max: 15, step: 0.5 },
    edge: { label: "Pooled edge", default: 0.8, min: 0, max: 1, step: 0.01 },
    granulation: { label: "Granulation", default: 0.4, min: 0, max: 1, step: 0.01 },
    streak: { label: "Turner streak", default: 0.35, min: 0, max: 1, step: 0.01 },
    wind: { label: "Wind", default: 1, min: 0, max: 3, step: 0.05 },
    blooms: { label: "Blooms", default: 5, min: 0, max: 8, step: 1 },
  },
  previewCamera: "sweep",
  Component: WashDome,
};

type Tune = Omit<Scene3dBackgroundPreset, "mode" | "textColor">;

const preset = (mode: "light" | "dark", p: Tune): Scene3dBackgroundPreset => ({
  ...p,
  mode,
  textColor: mode === "light" ? "#000000" : "#ffffff",
});

/** NSW south coast skies. The dome and floor paint on the backing tone, so `backing` is the paper colour. */
export const presets: Scene3dBackgroundPreset[] = [
  preset("light", {
    id: "p1",
    name: "Wattamolla",
    colors: ["#9ab3c6", "#879bb1", "#e1cdc3"],
    backing: "#f5f2eb",
    speed: 1,
    params: {
      coverage: 0.35,
      calmHeight: 9,
      edge: 0.8,
      granulation: 0.4,
      streak: 0.35,
      wind: 1,
      blooms: 5,
    },
  }),
  preset("light", {
    id: "p2",
    name: "Stanwell Park",
    colors: ["#a3c0d6", "#819bb5", "#eed8b4"],
    backing: "#f2f4f3",
    speed: 1.1,
    params: {
      coverage: 0.28,
      calmHeight: 11,
      edge: 0.6,
      granulation: 0.25,
      streak: 0.75,
      wind: 1.6,
      blooms: 3,
    },
  }),
  preset("light", {
    id: "p3",
    name: "Gerringong",
    colors: ["#a8bcb3", "#889c95", "#e4d3b3"],
    backing: "#f1f0e6",
    speed: 0.9,
    params: {
      coverage: 0.45,
      calmHeight: 9,
      edge: 0.9,
      granulation: 0.6,
      streak: 0.2,
      wind: 0.8,
      blooms: 6,
    },
  }),
  preset("light", {
    id: "p4",
    name: "Mollymook",
    colors: ["#d2b8a9", "#a8948c", "#f0d6c6"],
    backing: "#f7f0e8",
    speed: 1,
    params: {
      coverage: 0.3,
      calmHeight: 10,
      edge: 0.7,
      granulation: 0.35,
      streak: 0.5,
      wind: 1.2,
      blooms: 4,
    },
  }),
  preset("light", {
    id: "p5",
    name: "Jervis Bay",
    colors: ["#a1cacb", "#78a0a5", "#eae3c9"],
    backing: "#f3f6f1",
    speed: 0.8,
    params: {
      coverage: 0.22,
      calmHeight: 12,
      edge: 1,
      granulation: 0.5,
      streak: 0.15,
      wind: 0.7,
      blooms: 7,
    },
  }),
  preset("dark", {
    id: "p6",
    name: "Southerly Buster",
    colors: ["#30355a", "#141527", "#785a50"],
    backing: "#1d2238",
    speed: 1,
    params: {
      coverage: 0.35,
      calmHeight: 9,
      edge: 0.8,
      granulation: 0.4,
      streak: 0.35,
      wind: 1,
      blooms: 5,
    },
  }),
  preset("dark", {
    id: "p7",
    name: "Montague",
    colors: ["#28434a", "#0f1c20", "#6a5f43"],
    backing: "#16262b",
    speed: 0.9,
    params: {
      coverage: 0.25,
      calmHeight: 10,
      edge: 0.9,
      granulation: 0.3,
      streak: 0.6,
      wind: 0.7,
      blooms: 3,
    },
  }),
  preset("dark", {
    id: "p8",
    name: "Gulaga",
    colors: ["#3f3452", "#1a1424", "#7a5566"],
    backing: "#231c2e",
    speed: 1.1,
    params: {
      coverage: 0.5,
      calmHeight: 9,
      edge: 0.6,
      granulation: 0.7,
      streak: 0.2,
      wind: 1.3,
      blooms: 6,
    },
  }),
  preset("dark", {
    id: "p9",
    name: "Twofold Bay",
    colors: ["#2f4440", "#121c1b", "#586356"],
    backing: "#1a2624",
    speed: 1.2,
    params: {
      coverage: 0.4,
      calmHeight: 11,
      edge: 1,
      granulation: 0.5,
      streak: 0.8,
      wind: 1.8,
      blooms: 2,
    },
  }),
];
