import type { Scene3dBackgroundDef, Scene3dBackgroundPreset } from "../../types";
import { SkeletonClockwork } from "./SkeletonClockwork";
import { CLOCKWORK } from "./train";

/** Skeleton clockwork (kinetic): the pierced brass going train of a skeleton clock spread overhead, with gear-driven orrery trains, turning smoothly by default. */
export const look: Scene3dBackgroundDef = {
  id: "skeleton-clockwork",
  name: "Skeleton clockwork",
  family: "kinetic",
  colorSlots: [
    { label: "Wheel", fallback: "#62502f" },
    { label: "Arbor", fallback: "#34434a" },
    { label: "Frieze", fallback: "#2a2620" },
    { label: "Sheen", fallback: "#6a5a3c" },
  ],
  params: {
    module: { label: "Tooth size", default: 0.3, min: 0.2, max: 0.45, step: 0.01 },
    rate: { label: "Teeth per second", default: 0.5, min: 0, max: 1.5, step: 0.05 },
    planes: {
      label: "Ceiling planes",
      default: 3,
      min: 1,
      max: CLOCKWORK.maxPlanes,
      step: 1,
    },
    ceiling: { label: "Ceiling height", default: 4.8, min: 4, max: 7, step: 0.1 },
    frieze: { label: "Frieze radius", default: 20, min: 15, max: 28, step: 0.5 },
    tick: { label: "Deadbeat tick", default: 0, min: 0, max: 1, step: 0.05 },
    seed: { label: "Arrangement", default: 1, min: 1, max: 99, step: 1 },
  },
  previewCamera: "ceiling",
  Component: SkeletonClockwork,
};

const light = { mode: "light", textColor: "#000000" } as const;
const dark = { mode: "dark", textColor: "#ffffff" } as const;

/** Murray and Darling river towns and locks. p1 and p6 are the approved sketch palettes (p1's arbor lifted to the 0.315 Theme floor). */
export const presets: Scene3dBackgroundPreset[] = [
  {
    id: "p1",
    name: "Murrumbidgee",
    ...light,
    colors: ["#c9ad7f", "#8e9ca1", "#d8cfbf", "#e8dcc2"],
    backing: "#f7f3ea",
    speed: 1,
    params: {
      module: 0.3,
      rate: 0.5,
      planes: 3,
      ceiling: 4.8,
      frieze: 20,
      tick: 0,
      seed: 1,
    },
  },
  {
    id: "p2",
    name: "Wentworth",
    ...light,
    colors: ["#a3a07c", "#8f9c9f", "#d3d3c0", "#e4e4d0"],
    backing: "#f5f6ef",
    speed: 0.9,
    params: {
      module: 0.24,
      rate: 0.4,
      planes: 4,
      ceiling: 4.6,
      frieze: 22,
      tick: 0,
      seed: 6,
    },
  },
  {
    id: "p3",
    name: "Goolwa",
    ...light,
    colors: ["#98a9b1", "#ae9572", "#d2d9da", "#e5eae9"],
    backing: "#f3f6f6",
    speed: 1,
    params: {
      module: 0.36,
      rate: 0.6,
      planes: 2,
      ceiling: 4.4,
      frieze: 18,
      tick: 0,
      seed: 12,
    },
  },
  {
    id: "p4",
    name: "Mannum",
    ...light,
    colors: ["#bb917e", "#9a9aa5", "#dccbc4", "#eedccf"],
    backing: "#f9f3f0",
    speed: 1.1,
    params: {
      module: 0.28,
      rate: 0.55,
      planes: 3,
      ceiling: 5,
      frieze: 24,
      tick: 0,
      seed: 13,
    },
  },
  {
    id: "p5",
    name: "Tocumwal",
    ...light,
    colors: ["#c9b47a", "#9e9b90", "#e1d7ba", "#f0e6c6"],
    backing: "#faf6e9",
    speed: 0.8,
    params: {
      module: 0.32,
      rate: 0.45,
      planes: 3,
      ceiling: 4.6,
      frieze: 21,
      tick: 0,
      seed: 16,
    },
  },
  {
    id: "p6",
    name: "Echuca",
    ...dark,
    colors: ["#62502f", "#34434a", "#2a2620", "#6a5a3c"],
    backing: "#0e0d0c",
    speed: 1,
    params: {
      module: 0.3,
      rate: 0.5,
      planes: 3,
      ceiling: 4.8,
      frieze: 20,
      tick: 0,
      seed: 1,
    },
  },
  {
    id: "p7",
    name: "Torrumbarry",
    ...dark,
    colors: ["#614a3d", "#3b4347", "#272426", "#705749"],
    backing: "#0e0c0d",
    speed: 0.9,
    params: {
      module: 0.26,
      rate: 0.4,
      planes: 4,
      ceiling: 5.2,
      frieze: 23,
      tick: 0,
      seed: 10,
    },
  },
  {
    id: "p8",
    name: "Blanchetown",
    ...dark,
    colors: ["#4f5a40", "#3e3b33", "#22261f", "#5a6547"],
    backing: "#11130f",
    speed: 1.1,
    params: {
      module: 0.34,
      rate: 0.6,
      planes: 2,
      ceiling: 4.4,
      frieze: 19,
      tick: 0,
      seed: 14,
    },
  },
  {
    id: "p9",
    name: "Wilcannia",
    ...dark,
    colors: ["#4b5967", "#5e4e33", "#1f242b", "#566473"],
    backing: "#111318",
    speed: 1,
    params: {
      module: 0.3,
      rate: 0.5,
      planes: 3,
      ceiling: 5.6,
      frieze: 26,
      tick: 0,
      seed: 17,
    },
  },
];
