// GENERATED by scripts/prepare-emoji-fonts.mjs. Do not edit by hand.

/** First private-use codepoint reserved for emoji placeholder substitution. */
export const EMOJI_PUA_START = 0xe000;

/** Number of reserved placeholder codepoints (one per distinct emoji cluster in a string). */
export const EMOJI_PUA_COUNT = 1024;

/** Text-default symbol codepoints the bundled fallback face covers with real outlines. */
export const SYMBOLS_CODEPOINTS: ReadonlySet<number> = new Set([
  0x2190, 0x2191, 0x2192, 0x2193, 0x2194, 0x2195, 0x21a9, 0x21aa, 0x21ba, 0x21bb, 0x21d0, 0x21d1,
  0x21d2, 0x21d3, 0x21d4, 0x21e7, 0x2303, 0x2318, 0x2325, 0x232b, 0x23ce, 0x2212, 0x221e, 0x2248,
  0x2260, 0x2264, 0x2265, 0x25a0, 0x25a1, 0x25b2, 0x25b3, 0x25b6, 0x25b7, 0x25bc, 0x25bd, 0x25c0,
  0x25c1, 0x25c6, 0x25c7, 0x25ca, 0x25cb, 0x25cf, 0x25e6, 0x2605, 0x2606, 0x2610, 0x2611, 0x2612,
  0x2660, 0x2663, 0x2665, 0x2666, 0x266a, 0x266b, 0x26a0, 0x2713, 0x2714, 0x2715, 0x2716, 0x2717,
  0x2718, 0x2726, 0x2727, 0x2736, 0x2764, 0x2794, 0x27a4,
]);

/** Every fallback glyph warmed before frame 0: the shared emoji placeholder cell plus each symbol. */
export const FALLBACK_PRELOAD_CHARACTERS =
  "\ue000" +
  "\u2190\u2191\u2192\u2193\u2194\u2195\u21a9\u21aa\u21ba\u21bb\u21d0\u21d1\u21d2\u21d3\u21d4\u21e7\u2303\u2318\u2325\u232b\u23ce\u2212\u221e\u2248\u2260\u2264\u2265\u25a0\u25a1\u25b2\u25b3\u25b6\u25b7\u25bc\u25bd\u25c0\u25c1\u25c6\u25c7\u25ca\u25cb\u25cf\u25e6\u2605\u2606\u2610\u2611\u2612\u2660\u2663\u2665\u2666\u266a\u266b\u26a0\u2713\u2714\u2715\u2716\u2717\u2718\u2726\u2727\u2736\u2764\u2794\u27a4";
