import { goboCompanionSun } from "../../kit/gobo";
import type { Scene3dBackgroundPreset, Scene3dCompanionLighting } from "../../types";
import { IRIS_SUN } from "./iris";

/** Companion rig: a warm sun behind the back screen at the look's own elevation, so devices are lit from where the pools fall, over a low warm sunset environment. */
function companion(
  mode: "light" | "dark",
  elevationDeg: number,
  kelvin: number,
  intensity: number,
): Scene3dCompanionLighting {
  const dark = mode === "dark";
  return {
    environment: { source: "kookaburra:sunset", intensity: dark ? 0.35 : 0.7, rotationDeg: 180 },
    sun: goboCompanionSun({ ...IRIS_SUN, elevationDeg }, { intensity, kelvin, angularDeg: 2 }),
    ambient: dark ? 0.3 : 0.5,
  };
}

/** South-west Western Australian names. p1 and p6 are the approved sketch palettes. */
export const IRIS_SCREEN_PRESETS: Scene3dBackgroundPreset[] = [
  {
    id: "p1",
    name: "Yallingup",
    mode: "light",
    textColor: "#000000",
    colors: ["#a79880", "#f5e3bd", "#e8d9b8"],
    backing: "#f8f4ec",
    speed: 1,
    params: {
      radius: 15,
      panels: 40,
      cycle: 30,
      sunElevation: 22,
      pool: 0.6,
      clearRadius: 6,
      textCalm: 0.6,
    },
    lighting: companion("light", 22, 3200, 2),
  },
  {
    id: "p2",
    name: "Greens Pool",
    mode: "light",
    textColor: "#000000",
    colors: ["#8a9d9a", "#e4f0e8", "#cfe3dc"],
    backing: "#f1f7f4",
    speed: 0.9,
    params: {
      radius: 17,
      panels: 48,
      cycle: 26,
      sunElevation: 28,
      pool: 0.5,
      clearRadius: 6.5,
      textCalm: 0.55,
    },
    lighting: companion("light", 28, 4800, 1.8),
  },
  {
    id: "p3",
    name: "Boranup",
    mode: "light",
    textColor: "#000000",
    colors: ["#979d85", "#eeecd2", "#d9dcc2"],
    backing: "#f5f5ea",
    speed: 1.1,
    params: {
      radius: 13,
      panels: 36,
      cycle: 34,
      sunElevation: 16,
      pool: 0.72,
      clearRadius: 5.5,
      textCalm: 0.65,
    },
    lighting: companion("light", 16, 4200, 1.8),
  },
  {
    id: "p4",
    name: "Hamelin Bay",
    mode: "light",
    textColor: "#000000",
    colors: ["#b2958f", "#f7e2d4", "#ecd3cb"],
    backing: "#faf2ee",
    speed: 0.85,
    params: {
      radius: 19,
      panels: 56,
      cycle: 24,
      sunElevation: 30,
      pool: 0.45,
      clearRadius: 7,
      textCalm: 0.5,
    },
    lighting: companion("light", 30, 3600, 2),
  },
  {
    id: "p5",
    name: "Porongurup",
    mode: "light",
    textColor: "#000000",
    colors: ["#9d98a8", "#f3ead0", "#ddd6e2"],
    backing: "#f5f3f7",
    speed: 1.2,
    params: {
      radius: 14,
      panels: 44,
      cycle: 38,
      sunElevation: 14,
      pool: 0.8,
      clearRadius: 6,
      textCalm: 0.7,
    },
    lighting: companion("light", 14, 4000, 1.6),
  },
  {
    id: "p6",
    name: "Karijini",
    mode: "dark",
    textColor: "#ffffff",
    colors: ["#1c2524", "#8a6c3c", "#62533a"],
    backing: "#0b1110",
    speed: 1,
    params: {
      radius: 15,
      panels: 40,
      cycle: 30,
      sunElevation: 22,
      pool: 0.6,
      clearRadius: 6,
      textCalm: 0.6,
    },
    lighting: companion("dark", 22, 3000, 2.2),
  },
  {
    id: "p7",
    name: "Nornalup",
    mode: "dark",
    textColor: "#ffffff",
    colors: ["#1a2620", "#8c7a3e", "#4f5a3e"],
    backing: "#08100c",
    speed: 0.9,
    params: {
      radius: 16,
      panels: 48,
      cycle: 28,
      sunElevation: 26,
      pool: 0.55,
      clearRadius: 6.5,
      textCalm: 0.6,
    },
    lighting: companion("dark", 26, 2900, 2),
  },
  {
    id: "p8",
    name: "Stirling Range",
    mode: "dark",
    textColor: "#ffffff",
    colors: ["#1f2233", "#9a6c5c", "#5f4d68"],
    backing: "#0a0b14",
    speed: 1.1,
    params: {
      radius: 20,
      panels: 60,
      cycle: 36,
      sunElevation: 16,
      pool: 0.7,
      clearRadius: 7.5,
      textCalm: 0.65,
    },
    lighting: companion("dark", 16, 2700, 1.8),
  },
  {
    id: "p9",
    name: "Torndirrup",
    mode: "dark",
    textColor: "#ffffff",
    colors: ["#23282b", "#9a8660", "#545755"],
    backing: "#0c0e10",
    speed: 0.8,
    params: {
      radius: 12,
      panels: 38,
      cycle: 22,
      sunElevation: 34,
      pool: 0.5,
      clearRadius: 5,
      textCalm: 0.55,
    },
    lighting: companion("dark", 34, 3400, 2),
  },
];
