#!/usr/bin/env node
// Bakes the tap-highlight glow-dot animation into RGBA PNG frames for the ffmpeg
// overlay, plus the include_bytes! table edit.rs embeds. Maintainer-only; the output
// is committed. Run: node scripts/generate-tap-dot.mjs
//
// The curve and falloff MIRROR src/editor/tapAnimation.ts and .tap-glow in
// src/styles.css; keep all three in sync by hand.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { deflateSync } from "node:zlib";

const TAP_ANIMATION_DURATION_MS = 550;
const TAP_DOT_FRAME_COUNT = 36;
const FPS = 60;
const SIZE = 256;
// The dot at scale 1 fills SIZE / headroom so the 1.12 pulse never clips; edit.rs mirrors this when sizing the overlay (TAP_DOT_CANVAS_HEADROOM).
const CANVAS_HEADROOM = 1.15;

const lerp = (a, b, t) => a + (b - a) * t;
const easeOutCubic = (t) => 1 - (1 - t) ** 3;

/** Mirror of tapAnimation.ts tapDotFrame(): pop-in, pulse, settle, fade. */
function tapDotFrame(p) {
  if (p < 0.15) {
    const t = easeOutCubic(p / 0.15);
    return { opacity: lerp(0, 0.9, t), scale: lerp(0.4, 1, t) };
  }
  if (p < 0.4) {
    const t = (p - 0.15) / 0.25;
    return { opacity: lerp(0.9, 0.75, t), scale: lerp(1, 1.12, t) };
  }
  if (p < 0.65) {
    const t = (p - 0.4) / 0.25;
    return { opacity: lerp(0.75, 0.6, t), scale: lerp(1.12, 1, t) };
  }
  const t = (p - 0.65) / 0.35;
  return { opacity: lerp(0.6, 0, t), scale: lerp(1, 0.92, t) };
}

/** Mirror of .tap-glow's closest-side radial gradient: t is r over half the element. */
function falloff(t) {
  if (t <= 0.45) return lerp(0.95, 0.55, t / 0.45);
  if (t <= 0.7) return lerp(0.55, 0, (t - 0.45) / 0.25);
  return 0;
}

const CRC_TABLE = new Uint32Array(256);
for (let n = 0; n < 256; n++) {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  CRC_TABLE[n] = c >>> 0;
}

function crc32(buf) {
  let c = 0xffffffff;
  for (const byte of buf) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const head = Buffer.alloc(4);
  head.writeUInt32BE(data.length, 0);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const tail = Buffer.alloc(4);
  tail.writeUInt32BE(crc32(body), 0);
  return Buffer.concat([head, body, tail]);
}

function encodePng(size, rgba) {
  const signature = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // colour type: RGBA
  const raw = Buffer.alloc(size * (size * 4 + 1));
  for (let y = 0; y < size; y++) {
    const row = y * (size * 4 + 1);
    raw[row] = 0; // filter: none
    rgba.copy(raw, row + 1, y * size * 4, (y + 1) * size * 4);
  }
  return Buffer.concat([
    signature,
    chunk("IHDR", ihdr),
    chunk("IDAT", deflateSync(raw, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

function renderFrame(index) {
  const elapsedMs = (index * 1000) / FPS;
  const p = elapsedMs > TAP_ANIMATION_DURATION_MS ? null : elapsedMs / TAP_ANIMATION_DURATION_MS;
  const { opacity, scale } = p === null ? { opacity: 0, scale: 1 } : tapDotFrame(p);
  const half = ((SIZE / CANVAS_HEADROOM) * scale) / 2;
  const centre = SIZE / 2;
  const rgba = Buffer.alloc(SIZE * SIZE * 4);
  for (let y = 0; y < SIZE; y++) {
    for (let x = 0; x < SIZE; x++) {
      const r = Math.hypot(x + 0.5 - centre, y + 0.5 - centre);
      const alpha = opacity * falloff(r / half);
      const at = (y * SIZE + x) * 4;
      rgba[at] = 255;
      rgba[at + 1] = 255;
      rgba[at + 2] = 255;
      rgba[at + 3] = Math.round(alpha * 255);
    }
  }
  return encodePng(SIZE, rgba);
}

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(repoRoot, "src-tauri", "templates", "tapdot");
mkdirSync(outDir, { recursive: true });

const names = [];
for (let i = 0; i < TAP_DOT_FRAME_COUNT; i++) {
  const name = `tapdot_${String(i).padStart(2, "0")}.png`;
  writeFileSync(join(outDir, name), renderFrame(i));
  names.push(name);
}

const rust = [
  "// GENERATED by scripts/generate-tap-dot.mjs. Do not edit by hand.",
  "",
  "/// The tap-highlight glow-dot animation, one RGBA PNG per 60fps frame.",
  "pub static TAP_DOT_FRAMES: &[&[u8]] = &[",
  ...names.map((n) => `    include_bytes!("../templates/tapdot/${n}"),`),
  "];",
  "",
].join("\n");
writeFileSync(join(repoRoot, "src-tauri", "src", "tap_dot_frames.generated.rs"), rust);

console.log(`wrote ${names.length} frames to ${outDir} and tap_dot_frames.generated.rs`);
