/** Bundled looks for each shader background: 9 per effect (p1-p5 light, p6-p9 dark), applied wholesale by the inspector's preset tiles (colours, speed, zoom and params all land explicitly in the sidecar; rendering reads this module only through the live Theme preset's anchors, themePreset.ts). Every colour stop passes AA against the preset's textColor with margin (light stops stay above 0.30 relative luminance, dark below 0.125) so foreground text always reads over the moving fill; the rules live in docs/backgrounds.md. Preview stills regenerate via `kookaburra:run --action option-previews` from the `bgp-*` preview-lab fixtures; a vitest pins those fixtures to this data. */

export interface ShaderBackgroundPreset {
  /** Shader-scoped id (p1..p9); pair with the shader id, never unique alone. */
  id: string;
  name: string;
  /** Light presets carry black text at AA; dark presets carry white. */
  mode: "light" | "dark";
  /** AA-checked text colour over every stop (card metadata / contrast hints). */
  textColor: string;
  /** One hex per colour slot, in slot order. */
  colors: string[];
  speed?: number;
  scale?: number;
  params?: Record<string, number>;
}

export const SHADER_BACKGROUND_PRESETS: Record<string, ShaderBackgroundPreset[]> = {
  "mesh-gradient": [
    {
      id: "p1",
      name: "Shell Beach",
      mode: "light",
      textColor: "#000000",
      colors: ["#f6e9e4", "#eed7cf", "#e9cec7", "#f4e3da"],
      speed: 0.4,
      params: { distortion: 0.5, swirl: 0.08 },
    },
    {
      id: "p2",
      name: "Coastal Mist",
      mode: "light",
      textColor: "#000000",
      colors: ["#e8eff4", "#d6e2eb", "#c8d8e4", "#dfe9f0"],
      speed: 0.3,
      params: { distortion: 0.9, swirl: 0.05, grainOverlay: 0.12 },
    },
    {
      id: "p3",
      name: "Wattle",
      mode: "light",
      textColor: "#000000",
      colors: ["#f7f0d9", "#efe3ba", "#e9d9a6", "#f3ead0"],
      speed: 0.5,
      params: { distortion: 0.6, swirl: 0.3 },
    },
    {
      id: "p4",
      name: "Eucalypt",
      mode: "light",
      textColor: "#000000",
      colors: ["#e6eee7", "#d3e2d6", "#c2d6c7", "#dce8dd"],
      speed: 0.35,
      params: { distortion: 0.75, swirl: 0.15, grainMixer: 0.15 },
    },
    {
      id: "p5",
      name: "Jacaranda",
      mode: "light",
      textColor: "#000000",
      colors: ["#ede7f5", "#ded3ed", "#cfc0e2", "#e5dcf1"],
      speed: 0.45,
      params: { distortion: 0.95, swirl: 0.2 },
    },
    {
      id: "p6",
      name: "Bass Strait",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0c1827", "#244460", "#3e648a", "#152a3f"],
      speed: 0.4,
      params: { distortion: 0.7, swirl: 0.12 },
    },
    {
      id: "p7",
      name: "Jarrah",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#21130c", "#563321", "#85572e", "#341f13"],
      speed: 0.3,
      params: { distortion: 0.55, swirl: 0.25, grainMixer: 0.2 },
    },
    {
      id: "p8",
      name: "Karri",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0d1912", "#294c36", "#416a4c", "#15281b"],
      speed: 0.45,
      params: { distortion: 0.85, swirl: 0.1, grainOverlay: 0.15 },
    },
    {
      id: "p9",
      name: "Bush Dusk",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#1a1025", "#3f2b5a", "#6e5596", "#241637"],
      speed: 0.5,
      params: { distortion: 0.9, swirl: 0.35 },
    },
  ],
  "simplex-noise": [
    {
      id: "p1",
      name: "Salt Lake",
      mode: "light",
      textColor: "#000000",
      colors: ["#f9f3f0", "#f3e6e0", "#edd9d1", "#e7ccc2", "#e2bfb3"],
      speed: 0.4,
      params: { stepsPerColor: 1, softness: 0.9 },
    },
    {
      id: "p2",
      name: "Spinifex",
      mode: "light",
      textColor: "#000000",
      colors: ["#f7f2e2", "#f0e7c8", "#e9dcae", "#e2d194", "#dcc77e"],
      speed: 0.45,
      params: { stepsPerColor: 3, softness: 0.15 },
    },
    {
      id: "p3",
      name: "Sea Glass",
      mode: "light",
      textColor: "#000000",
      colors: ["#eef6f3", "#d9ece6", "#c4e2d8", "#afd7ca", "#9acdbd"],
      speed: 0.4,
      params: { stepsPerColor: 2, softness: 0.5 },
    },
    {
      id: "p4",
      name: "Paperbark",
      mode: "light",
      textColor: "#000000",
      colors: ["#f9f5ee", "#f1e9db", "#e9dcc8", "#e1d0b5", "#d9c4a3"],
      speed: 0.3,
      params: { stepsPerColor: 4, softness: 0.25 },
    },
    {
      id: "p5",
      name: "Daintree Mist",
      mode: "light",
      textColor: "#000000",
      colors: ["#f0f5ee", "#dfe9da", "#cdddc6", "#bcd1b2", "#abc59f"],
      speed: 0.5,
      params: { stepsPerColor: 1, softness: 1 },
    },
    {
      id: "p6",
      name: "Nullarbor Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0b101e", "#141e32", "#21314b", "#32476a", "#466291"],
      speed: 0.4,
      params: { stepsPerColor: 2, softness: 0.6 },
    },
    {
      id: "p7",
      name: "Billabong",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#071411", "#10251f", "#1a3a2f", "#265243", "#336b58"],
      speed: 0.35,
      params: { stepsPerColor: 3, softness: 0.2 },
    },
    {
      id: "p8",
      name: "Uluru Dusk",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#180d0d", "#2f1a17", "#502e27", "#6d4034", "#8b5342"],
      speed: 0.45,
      params: { stepsPerColor: 5, softness: 0.35 },
    },
    {
      id: "p9",
      name: "Tasman Deep",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0c1219", "#19232f", "#2b3a4a", "#3c4e62", "#4d637b"],
      speed: 0.5,
      params: { stepsPerColor: 1, softness: 0.95 },
    },
  ],
  swirl: [
    {
      id: "p1",
      name: "Whitsunday",
      mode: "light",
      textColor: "#000000",
      colors: ["#eaf4f6", "#cfe7ec", "#bcdde5", "#dceef1"],
      speed: 0.4,
      params: { bandCount: 4, twist: 0.1, softness: 0.4 },
    },
    {
      id: "p2",
      name: "Frangipani",
      mode: "light",
      textColor: "#000000",
      colors: ["#f8f3ea", "#f5e9cd", "#f2dcd4", "#f6efe0"],
      speed: 0.35,
      params: { bandCount: 3, twist: 0.06, softness: 0.7, proportion: 0.6 },
    },
    {
      id: "p3",
      name: "Lilly Pilly",
      mode: "light",
      textColor: "#000000",
      colors: ["#f5ecf2", "#e9d5e4", "#dcc2d6", "#efe0ea"],
      speed: 0.5,
      params: { bandCount: 7, twist: 0.2, softness: 0.2 },
    },
    {
      id: "p4",
      name: "Dune",
      mode: "light",
      textColor: "#000000",
      colors: ["#f6f1e7", "#eadfc5", "#ded0ab", "#f0e8d6"],
      speed: 0.3,
      params: { bandCount: 5, twist: 0.08, softness: 0.5, noise: 0.15, noiseFrequency: 0.3 },
    },
    {
      id: "p5",
      name: "Morning Tide",
      mode: "light",
      textColor: "#000000",
      colors: ["#edf4f0", "#d5e6df", "#bfd9cf", "#e2eee8"],
      speed: 0.45,
      params: { bandCount: 9, twist: 0.14, softness: 0.35 },
    },
    {
      id: "p6",
      name: "Southern Ocean",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#09141d", "#1d3d55", "#366687", "#102430"],
      speed: 0.4,
      params: { bandCount: 5, twist: 0.16, softness: 0.3 },
    },
    {
      id: "p7",
      name: "Ironbark",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#140f0c", "#443322", "#765d40", "#251b12"],
      speed: 0.3,
      params: { bandCount: 3, twist: 0.28, softness: 0.15, proportion: 0.55 },
    },
    {
      id: "p8",
      name: "Mangrove",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0c1410", "#22432d", "#3c6b4a", "#152519"],
      speed: 0.45,
      params: { bandCount: 8, twist: 0.1, softness: 0.45, noise: 0.12, noiseFrequency: 0.25 },
    },
    {
      id: "p9",
      name: "Cradle Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#110f1f", "#373262", "#6158a1", "#1b1831"],
      speed: 0.5,
      params: { bandCount: 6, twist: 0.22, softness: 0.25 },
    },
  ],
  "neuro-noise": [
    {
      id: "p1",
      name: "Snowgum",
      mode: "light",
      textColor: "#000000",
      colors: ["#ffffff", "#ccd9d2", "#ecf1ee"],
      speed: 0.4,
      params: { brightness: 0.08, contrast: 0.15 },
    },
    {
      id: "p2",
      name: "Tea Tree",
      mode: "light",
      textColor: "#000000",
      colors: ["#fbfdf9", "#c3d9c0", "#e8f1e5"],
      speed: 0.45,
      params: { brightness: 0.06, contrast: 0.3 },
    },
    {
      id: "p3",
      name: "Coral Shallows",
      mode: "light",
      textColor: "#000000",
      colors: ["#fdf9f6", "#ecc9bc", "#f7e8e0"],
      speed: 0.5,
      params: { brightness: 0.05, contrast: 0.4 },
    },
    {
      id: "p4",
      name: "Hinterland",
      mode: "light",
      textColor: "#000000",
      colors: ["#f9fbfa", "#b8cdc9", "#e4ecea"],
      speed: 0.3,
      params: { brightness: 0.1, contrast: 0.12 },
    },
    {
      id: "p5",
      name: "Bluegum",
      mode: "light",
      textColor: "#000000",
      colors: ["#f9fbfd", "#b5c7d8", "#e2eaf1"],
      speed: 0.4,
      params: { brightness: 0.07, contrast: 0.25 },
    },
    {
      id: "p6",
      name: "Basalt",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#546371", "#242b33", "#0b0e12"],
      speed: 0.4,
      params: { brightness: 0.07, contrast: 0.35 },
    },
    {
      id: "p7",
      name: "Kimberley Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#8d523b", "#311c14", "#100a08"],
      speed: 0.35,
      params: { brightness: 0.06, contrast: 0.45 },
    },
    {
      id: "p8",
      name: "Deep Reef",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#2b6b65", "#183b38", "#071211"],
      speed: 0.45,
      params: { brightness: 0.08, contrast: 0.4 },
    },
    {
      id: "p9",
      name: "Brindabella",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#555c9d", "#292c51", "#0c0d19"],
      speed: 0.5,
      params: { brightness: 0.05, contrast: 0.5 },
    },
  ],
  warp: [
    {
      id: "p1",
      name: "Sandstone",
      mode: "light",
      textColor: "#000000",
      colors: ["#f4ede1", "#e3cfa9", "#ede2cd", "#dcc394"],
      speed: 0.4,
      params: { proportion: 0.5, softness: 1, distortion: 0.2, swirl: 0.6 },
    },
    {
      id: "p2",
      name: "Banksia",
      mode: "light",
      textColor: "#000000",
      colors: ["#f7efe6", "#eccdb0", "#f2e0d0", "#e4b990"],
      speed: 0.35,
      params: { shape: 1, shapeScale: 0.25, swirl: 0.5, softness: 0.85 },
    },
    {
      id: "p3",
      name: "Melaleuca",
      mode: "light",
      textColor: "#000000",
      colors: ["#eff4f0", "#c9dcd0", "#dfe9e2", "#b7d0c1"],
      speed: 0.45,
      params: { shape: 2, shapeScale: 0.2, swirl: 0.7, distortion: 0.3, softness: 0.8 },
    },
    {
      id: "p4",
      name: "High Country",
      mode: "light",
      textColor: "#000000",
      colors: ["#eef2f6", "#c3d3e2", "#dde6ee", "#aec3d6"],
      speed: 0.3,
      params: { proportion: 0.4, softness: 0.9, distortion: 0.35, swirl: 0.9, swirlIterations: 14 },
    },
    {
      id: "p5",
      name: "Freshwater",
      mode: "light",
      textColor: "#000000",
      colors: ["#edf5f5", "#c2e0e0", "#dcedec", "#a9d2d2"],
      speed: 0.5,
      params: { proportion: 0.45, softness: 1, distortion: 0.15, swirl: 0.45 },
    },
    {
      id: "p6",
      name: "Outback Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#140d07", "#6c4925", "#2b1c0f", "#865727"],
      speed: 0.4,
      params: { proportion: 0.5, softness: 1, distortion: 0.2, swirl: 0.6 },
    },
    {
      id: "p7",
      name: "Top End",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#091418", "#1f515c", "#112631", "#306972"],
      speed: 0.45,
      params: { shape: 1, shapeScale: 0.3, swirl: 0.75, softness: 0.8, swirlIterations: 12 },
    },
    {
      id: "p8",
      name: "Blue Mountains",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0d111a", "#3e4b7c", "#192134", "#4f5e99"],
      speed: 0.3,
      params: { shape: 2, shapeScale: 0.15, swirl: 0.5, distortion: 0.3, softness: 0.9 },
    },
    {
      id: "p9",
      name: "Bogong",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#13100c", "#5a5242", "#252016", "#69604f"],
      speed: 0.35,
      params: { proportion: 0.55, softness: 0.85, distortion: 0.4, swirl: 1, swirlIterations: 16 },
    },
  ],
  "smoke-ring": [
    {
      id: "p1",
      name: "Ghost Gum",
      mode: "light",
      textColor: "#000000",
      colors: ["#f2f4f1", "#b9c6bb"],
      speed: 0.4,
      params: { thickness: 0.7, radius: 0.25, innerShape: 0.7, noiseScale: 2.6 },
    },
    {
      id: "p2",
      name: "Lake Hillier",
      mode: "light",
      textColor: "#000000",
      colors: ["#f7eef0", "#e3b8c4"],
      speed: 0.35,
      params: { thickness: 0.45, radius: 0.32, innerShape: 1.4, noiseScale: 2 },
    },
    {
      id: "p3",
      name: "Rock Pool",
      mode: "light",
      textColor: "#000000",
      colors: ["#edf4f4", "#a5cbc9"],
      speed: 0.45,
      params: {
        thickness: 0.8,
        radius: 0.22,
        innerShape: 0.5,
        noiseScale: 3.4,
        noiseIterations: 6,
      },
    },
    {
      id: "p4",
      name: "Opal",
      mode: "light",
      textColor: "#000000",
      colors: ["#f1f2f6", "#b3bedd"],
      speed: 0.5,
      params: { thickness: 0.55, radius: 0.3, innerShape: 1, noiseScale: 1.6, noiseIterations: 3 },
    },
    {
      id: "p5",
      name: "Sun Shower",
      mode: "light",
      textColor: "#000000",
      colors: ["#f8f4ea", "#dcc9a0"],
      speed: 0.3,
      params: { thickness: 0.85, radius: 0.2, innerShape: 0.4, noiseScale: 3.8 },
    },
    {
      id: "p6",
      name: "Ningaloo",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#04100f", "#2d6b63"],
      speed: 0.4,
      params: { thickness: 0.65, radius: 0.25, innerShape: 0.7, noiseScale: 2.8 },
    },
    {
      id: "p7",
      name: "Bunya",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0a0f0a", "#456b3a"],
      speed: 0.35,
      params: {
        thickness: 0.85,
        radius: 0.2,
        innerShape: 0.45,
        noiseScale: 3.6,
        noiseIterations: 7,
      },
    },
    {
      id: "p8",
      name: "Yarra Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0a0c15", "#515ca1"],
      speed: 0.5,
      params: { thickness: 0.5, radius: 0.32, innerShape: 1.3, noiseScale: 2.2 },
    },
    {
      id: "p9",
      name: "Red Centre",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#120b08", "#964d36"],
      speed: 0.4,
      params: {
        thickness: 0.75,
        radius: 0.24,
        innerShape: 0.55,
        noiseScale: 4.2,
        noiseIterations: 5,
      },
    },
  ],
  "dot-grid": [
    {
      id: "p1",
      name: "Cottesloe",
      mode: "light",
      textColor: "#000000",
      colors: ["#edf3f9", "#e1ebf4", "#d6e7f3"],
      speed: 1,
      params: { density: 50, dotSize: 0.19, pulse: 0.45, waveWidth: 0.5, driftAngle: 70 },
    },
    {
      id: "p2",
      name: "Hyams",
      mode: "light",
      textColor: "#000000",
      colors: ["#ebf4f7", "#ddedf0", "#d0eaec"],
      speed: 0.7,
      params: { density: 64, dotSize: 0.15, pulse: 0.3, waveWidth: 0.75, driftAngle: 110 },
    },
    {
      id: "p3",
      name: "Noosa",
      mode: "light",
      textColor: "#000000",
      colors: ["#f6f2e9", "#f0e9dd", "#f0e3d3"],
      speed: 0.9,
      params: { density: 38, dotSize: 0.24, pulse: 0.6, waveWidth: 0.4, driftAngle: 25 },
    },
    {
      id: "p4",
      name: "Clare Valley",
      mode: "light",
      textColor: "#000000",
      colors: ["#ebf5e9", "#e0eedb", "#d9eace"],
      speed: 0.6,
      params: { density: 56, dotSize: 0.17, pulse: 0.5, waveWidth: 0.35, driftAngle: 60 },
    },
    {
      id: "p5",
      name: "Freycinet",
      mode: "light",
      textColor: "#000000",
      colors: ["#fceff1", "#f9e5e8", "#fcdde0"],
      speed: 1.2,
      params: { density: 44, dotSize: 0.22, pulse: 0.7, waveWidth: 0.6, driftAngle: 205 },
    },
    {
      id: "p6",
      name: "Arafura",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0f141b", "#2e405b", "#416198"],
      speed: 1,
      params: { density: 50, dotSize: 0.19, pulse: 0.45, waveWidth: 0.5, driftAngle: 70 },
    },
    {
      id: "p7",
      name: "Warrumbungle",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#17121e", "#4e3465", "#7f48a7"],
      speed: 0.7,
      params: { density: 66, dotSize: 0.14, pulse: 0.4, waveWidth: 0.9, driftAngle: 120 },
    },
    {
      id: "p8",
      name: "Coober Pedy",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0c1616", "#224541", "#2c6c5f"],
      speed: 0.9,
      params: { density: 40, dotSize: 0.23, pulse: 0.65, waveWidth: 0.4, driftAngle: 300 },
    },
    {
      id: "p9",
      name: "Menindee",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#19130e", "#513b28", "#855738"],
      speed: 0.6,
      params: { density: 58, dotSize: 0.16, pulse: 0.55, waveWidth: 0.65, driftAngle: 15 },
    },
  ],
  "graph-grid": [
    {
      id: "p1",
      name: "Rottnest",
      mode: "light",
      textColor: "#000000",
      colors: ["#ebf4f5", "#dff0f0", "#d3eaeb", "#e6f2f2"],
      speed: 0.85,
      params: {
        density: 12,
        lineWeight: 0.4,
        highlightWidth: 0.35,
        fillDensity: 0.18,
        cadence: 0.25,
      },
    },
    {
      id: "p2",
      name: "Barossa",
      mode: "light",
      textColor: "#000000",
      colors: ["#faf0f2", "#fae8ec", "#f9e0e5", "#f9edef"],
      speed: 0.3,
      params: {
        density: 9,
        lineWeight: 0.55,
        highlightWidth: 0.5,
        fillDensity: 0.1,
        cadence: 0.15,
      },
    },
    {
      id: "p3",
      name: "Otway",
      mode: "light",
      textColor: "#000000",
      colors: ["#ebf5ed", "#e0f1e1", "#d4ecd6", "#e7f3e7"],
      speed: 0.45,
      params: {
        density: 16,
        lineWeight: 0.3,
        highlightWidth: 0.25,
        fillDensity: 0.28,
        cadence: 0.35,
      },
    },
    {
      id: "p4",
      name: "Ninety Mile",
      mode: "light",
      textColor: "#000000",
      colors: ["#f5f2eb", "#f1ece0", "#ede5d5", "#f4efe8"],
      speed: 0.35,
      params: {
        density: 20,
        lineWeight: 0.25,
        highlightWidth: 0.6,
        fillDensity: 0.08,
        cadence: 0.2,
      },
    },
    {
      id: "p5",
      name: "Palm Cove",
      mode: "light",
      textColor: "#000000",
      colors: ["#edf3f7", "#e2eef3", "#d7e9ef", "#e8f2f4"],
      speed: 0.5,
      params: {
        density: 11,
        lineWeight: 0.5,
        highlightWidth: 0.3,
        fillDensity: 0.22,
        cadence: 0.3,
      },
    },
    {
      id: "p6",
      name: "Simpson Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#18100d", "#5e3e30", "#8a543b", "#3e2f25"],
      speed: 0.85,
      params: {
        density: 12,
        lineWeight: 0.4,
        highlightWidth: 0.35,
        fillDensity: 0.18,
        cadence: 0.25,
      },
    },
    {
      id: "p7",
      name: "Gippsland",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0a140f", "#264d37", "#2d6d48", "#203728"],
      speed: 0.35,
      params: {
        density: 15,
        lineWeight: 0.35,
        highlightWidth: 0.45,
        fillDensity: 0.25,
        cadence: 0.35,
      },
    },
    {
      id: "p8",
      name: "Macquarie",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0d1218", "#2f485c", "#3a6588", "#25343e"],
      speed: 0.3,
      params: {
        density: 8,
        lineWeight: 0.6,
        highlightWidth: 0.55,
        fillDensity: 0.12,
        cadence: 0.15,
      },
    },
    {
      id: "p9",
      name: "Timor Deep",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#11111d", "#403f79", "#5654be", "#312f4c"],
      speed: 0.45,
      params: {
        density: 18,
        lineWeight: 0.3,
        highlightWidth: 0.28,
        fillDensity: 0.3,
        cadence: 0.4,
      },
    },
  ],
  "horizon-grid": [
    {
      id: "p1",
      name: "Cable Beach",
      mode: "light",
      textColor: "#000000",
      colors: ["#eaf4f4", "#d9eceb", "#d8f0ed"],
      speed: 0.4,
      params: { horizon: 0.05, density: 14, lineWeight: 0.4, glow: 0.5, fade: 0.6 },
    },
    {
      id: "p2",
      name: "Airlie",
      mode: "light",
      textColor: "#000000",
      colors: ["#edf3f7", "#deeaf1", "#ddeef5"],
      speed: 0.35,
      params: { horizon: 0.12, density: 10, lineWeight: 0.5, glow: 0.65, fade: 0.5 },
    },
    {
      id: "p3",
      name: "Esperance",
      mode: "light",
      textColor: "#000000",
      colors: ["#eef3f8", "#e0eaf3", "#dfedf7"],
      speed: 0.3,
      params: { horizon: 0, density: 18, lineWeight: 0.3, glow: 0.4, fade: 0.7 },
    },
    {
      id: "p4",
      name: "Wilpena",
      mode: "light",
      textColor: "#000000",
      colors: ["#f7f1ed", "#f3e6df", "#f9e8e0"],
      speed: 0.45,
      params: { horizon: 0.08, density: 12, lineWeight: 0.45, glow: 0.55, fade: 0.45 },
    },
    {
      id: "p5",
      name: "Broome",
      mode: "light",
      textColor: "#000000",
      colors: ["#f8f1ee", "#f4e6e0", "#f8e8e0"],
      speed: 0.5,
      params: { horizon: -0.05, density: 15, lineWeight: 0.35, glow: 0.7, fade: 0.55 },
    },
    {
      id: "p6",
      name: "Strzelecki",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#150e0b", "#6b4c37", "#805936"],
      speed: 0.4,
      params: { horizon: 0.05, density: 14, lineWeight: 0.4, glow: 0.5, fade: 0.6 },
    },
    {
      id: "p7",
      name: "Snowy Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0c1017", "#3d5375", "#3d638f"],
      speed: 0.3,
      params: { horizon: 0.1, density: 20, lineWeight: 0.3, glow: 0.35, fade: 0.75 },
    },
    {
      id: "p8",
      name: "Port Davey",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#091112", "#2f595d", "#2d6a6c"],
      speed: 0.35,
      params: { horizon: 0, density: 11, lineWeight: 0.5, glow: 0.6, fade: 0.5 },
    },
    {
      id: "p9",
      name: "Arnhem",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#150d17", "#6f407a", "#8e429a"],
      speed: 0.45,
      params: { horizon: -0.08, density: 16, lineWeight: 0.35, glow: 0.75, fade: 0.4 },
    },
  ],
  "hex-grid": [
    {
      id: "p1",
      name: "Bronte",
      mode: "light",
      textColor: "#000000",
      colors: ["#e9f3f2", "#deefeb", "#d5ebe4"],
      speed: 0.85,
      params: { density: 9, lineWeight: 0.35, glow: 0.6, softness: 0.5, cadence: 1 },
    },
    {
      id: "p2",
      name: "Mission Beach",
      mode: "light",
      textColor: "#000000",
      colors: ["#eaf4ed", "#deefe3", "#d6ebda"],
      speed: 0.35,
      params: { density: 6, lineWeight: 0.5, glow: 0.5, softness: 0.7, cadence: 0.7 },
    },
    {
      id: "p3",
      name: "Atherton",
      mode: "light",
      textColor: "#000000",
      colors: ["#eaf4ea", "#e0efde", "#d9ebd6"],
      speed: 0.3,
      params: { density: 12, lineWeight: 0.28, glow: 0.45, softness: 0.35, cadence: 1.3 },
    },
    {
      id: "p4",
      name: "Kata Tjuta",
      mode: "light",
      textColor: "#000000",
      colors: ["#f6f0ed", "#f5e9e4", "#f3e2dd"],
      speed: 0.45,
      params: { density: 8, lineWeight: 0.45, glow: 0.7, softness: 0.6, cadence: 0.9 },
    },
    {
      id: "p5",
      name: "Shark Bay",
      mode: "light",
      textColor: "#000000",
      colors: ["#ecf2f5", "#e1edf2", "#d8e9ee"],
      speed: 0.5,
      params: { density: 14, lineWeight: 0.3, glow: 0.55, softness: 0.4, cadence: 1.1 },
    },
    {
      id: "p6",
      name: "Litchfield",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0c1612", "#224635", "#2c6b49"],
      speed: 0.85,
      params: { density: 9, lineWeight: 0.35, glow: 0.6, softness: 0.5, cadence: 1 },
    },
    {
      id: "p7",
      name: "Undara",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#19130e", "#503b28", "#7a5933"],
      speed: 0.35,
      params: { density: 7, lineWeight: 0.5, glow: 0.75, softness: 0.65, cadence: 0.8 },
    },
    {
      id: "p8",
      name: "Torres",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0f151a", "#2d4159", "#3f6092"],
      speed: 0.45,
      params: { density: 12, lineWeight: 0.3, glow: 0.5, softness: 0.35, cadence: 1.2 },
    },
    {
      id: "p9",
      name: "Ben Lomond",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#16121f", "#483668", "#734aab"],
      speed: 0.3,
      params: { density: 10, lineWeight: 0.4, glow: 0.65, softness: 0.55, cadence: 0.6 },
    },
  ],
};
