/** Bundled looks for each shader background: 9 per effect (p1-p5 light, p6-p9 dark), applied wholesale by the inspector's preset tiles (colours, speed, zoom and params all land explicitly in the sidecar, so rendering never reads this module). Every colour stop passes AA against the preset's textColor with margin (light stops stay above 0.30 relative luminance, dark below 0.125) so foreground text always reads over the moving fill; the rules live in docs/backgrounds.md. Preview stills regenerate via `kookaburra:run --action option-previews` from the `bgp-*` preview-lab fixtures; a vitest pins those fixtures to this data. */

export interface ShaderBackgroundPreset {
  /** Shader-scoped id (p1..p9); pair with the shader id, never unique alone. */
  id: string;
  name: string;
  /** Light presets carry black text at AA; dark presets carry white. */
  mode: "light" | "dark";
  /** AA-checked text colour over every stop (card metadata / contrast hints). */
  textColor: string;
  /** One hex per colour slot, in slot order. */
  colors: string[];
  speed?: number;
  scale?: number;
  params?: Record<string, number>;
}

export const SHADER_BACKGROUND_PRESETS: Record<string, ShaderBackgroundPreset[]> = {
  "mesh-gradient": [
    {
      id: "p1",
      name: "Shell Beach",
      mode: "light",
      textColor: "#000000",
      colors: ["#f6e9e4", "#eed7cf", "#e9cec7", "#f4e3da"],
      speed: 0.4,
      params: { distortion: 0.5, swirl: 0.08 },
    },
    {
      id: "p2",
      name: "Coastal Mist",
      mode: "light",
      textColor: "#000000",
      colors: ["#e8eff4", "#d6e2eb", "#c8d8e4", "#dfe9f0"],
      speed: 0.3,
      params: { distortion: 0.9, swirl: 0.05, grainOverlay: 0.12 },
    },
    {
      id: "p3",
      name: "Wattle",
      mode: "light",
      textColor: "#000000",
      colors: ["#f7f0d9", "#efe3ba", "#e9d9a6", "#f3ead0"],
      speed: 0.5,
      params: { distortion: 0.6, swirl: 0.3 },
    },
    {
      id: "p4",
      name: "Eucalypt",
      mode: "light",
      textColor: "#000000",
      colors: ["#e6eee7", "#d3e2d6", "#c2d6c7", "#dce8dd"],
      speed: 0.35,
      params: { distortion: 0.75, swirl: 0.15, grainMixer: 0.15 },
    },
    {
      id: "p5",
      name: "Jacaranda",
      mode: "light",
      textColor: "#000000",
      colors: ["#ede7f5", "#ded3ed", "#cfc0e2", "#e5dcf1"],
      speed: 0.45,
      params: { distortion: 0.95, swirl: 0.2 },
    },
    {
      id: "p6",
      name: "Bass Strait",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0d1826", "#26425c", "#406285", "#16293c"],
      speed: 0.4,
      params: { distortion: 0.7, swirl: 0.12 },
    },
    {
      id: "p7",
      name: "Jarrah",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#20130d", "#4f3021", "#7a5230", "#331f15"],
      speed: 0.3,
      params: { distortion: 0.55, swirl: 0.25, grainMixer: 0.2 },
    },
    {
      id: "p8",
      name: "Karri",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0e1912", "#2b4a36", "#43684d", "#16281c"],
      speed: 0.45,
      params: { distortion: 0.85, swirl: 0.1, grainOverlay: 0.15 },
    },
    {
      id: "p9",
      name: "Bush Dusk",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#1a1024", "#3d2b56", "#6b5490", "#241736"],
      speed: 0.5,
      params: { distortion: 0.9, swirl: 0.35 },
    },
  ],
  "simplex-noise": [
    {
      id: "p1",
      name: "Salt Lake",
      mode: "light",
      textColor: "#000000",
      colors: ["#f9f3f0", "#f3e6e0", "#edd9d1", "#e7ccc2", "#e2bfb3"],
      speed: 0.4,
      params: { stepsPerColor: 1, softness: 0.9 },
    },
    {
      id: "p2",
      name: "Spinifex",
      mode: "light",
      textColor: "#000000",
      colors: ["#f7f2e2", "#f0e7c8", "#e9dcae", "#e2d194", "#dcc77e"],
      speed: 0.45,
      params: { stepsPerColor: 3, softness: 0.15 },
    },
    {
      id: "p3",
      name: "Sea Glass",
      mode: "light",
      textColor: "#000000",
      colors: ["#eef6f3", "#d9ece6", "#c4e2d8", "#afd7ca", "#9acdbd"],
      speed: 0.4,
      params: { stepsPerColor: 2, softness: 0.5 },
    },
    {
      id: "p4",
      name: "Paperbark",
      mode: "light",
      textColor: "#000000",
      colors: ["#f9f5ee", "#f1e9db", "#e9dcc8", "#e1d0b5", "#d9c4a3"],
      speed: 0.3,
      params: { stepsPerColor: 4, softness: 0.25 },
    },
    {
      id: "p5",
      name: "Daintree Mist",
      mode: "light",
      textColor: "#000000",
      colors: ["#f0f5ee", "#dfe9da", "#cdddc6", "#bcd1b2", "#abc59f"],
      speed: 0.5,
      params: { stepsPerColor: 1, softness: 1 },
    },
    {
      id: "p6",
      name: "Nullarbor Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0b101d", "#151e31", "#223048", "#334666", "#47608c"],
      speed: 0.4,
      params: { stepsPerColor: 2, softness: 0.6 },
    },
    {
      id: "p7",
      name: "Billabong",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#081411", "#12251f", "#1d3a30", "#2a5244", "#386b59"],
      speed: 0.35,
      params: { stepsPerColor: 3, softness: 0.2 },
    },
    {
      id: "p8",
      name: "Uluru Dusk",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#170d0d", "#2e1a18", "#472a24", "#613b31", "#7c4c3e"],
      speed: 0.45,
      params: { stepsPerColor: 5, softness: 0.35 },
    },
    {
      id: "p9",
      name: "Tasman Deep",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0d1218", "#1b232d", "#2a3542", "#3a4858", "#4b5c6f"],
      speed: 0.5,
      params: { stepsPerColor: 1, softness: 0.95 },
    },
  ],
  swirl: [
    {
      id: "p1",
      name: "Whitsunday",
      mode: "light",
      textColor: "#000000",
      colors: ["#eaf4f6", "#cfe7ec", "#bcdde5", "#dceef1"],
      speed: 0.4,
      params: { bandCount: 4, twist: 0.1, softness: 0.4 },
    },
    {
      id: "p2",
      name: "Frangipani",
      mode: "light",
      textColor: "#000000",
      colors: ["#f8f3ea", "#f5e9cd", "#f2dcd4", "#f6efe0"],
      speed: 0.35,
      params: { bandCount: 3, twist: 0.06, softness: 0.7, proportion: 0.6 },
    },
    {
      id: "p3",
      name: "Lilly Pilly",
      mode: "light",
      textColor: "#000000",
      colors: ["#f5ecf2", "#e9d5e4", "#dcc2d6", "#efe0ea"],
      speed: 0.5,
      params: { bandCount: 7, twist: 0.2, softness: 0.2 },
    },
    {
      id: "p4",
      name: "Dune",
      mode: "light",
      textColor: "#000000",
      colors: ["#f6f1e7", "#eadfc5", "#ded0ab", "#f0e8d6"],
      speed: 0.3,
      params: { bandCount: 5, twist: 0.08, softness: 0.5, noise: 0.15, noiseFrequency: 0.3 },
    },
    {
      id: "p5",
      name: "Morning Tide",
      mode: "light",
      textColor: "#000000",
      colors: ["#edf4f0", "#d5e6df", "#bfd9cf", "#e2eee8"],
      speed: 0.45,
      params: { bandCount: 9, twist: 0.14, softness: 0.35 },
    },
    {
      id: "p6",
      name: "Southern Ocean",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0a141c", "#1e3a50", "#38617f", "#12242f"],
      speed: 0.4,
      params: { bandCount: 5, twist: 0.16, softness: 0.3 },
    },
    {
      id: "p7",
      name: "Ironbark",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#140f0c", "#3a2c1e", "#66513a", "#241b13"],
      speed: 0.3,
      params: { bandCount: 3, twist: 0.28, softness: 0.15, proportion: 0.55 },
    },
    {
      id: "p8",
      name: "Mangrove",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0d1410", "#24422e", "#3f6a4c", "#16251a"],
      speed: 0.45,
      params: { bandCount: 8, twist: 0.1, softness: 0.45, noise: 0.12, noiseFrequency: 0.25 },
    },
    {
      id: "p9",
      name: "Cradle Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#110f1e", "#2d2950", "#514a85", "#1b1830"],
      speed: 0.5,
      params: { bandCount: 6, twist: 0.22, softness: 0.25 },
    },
  ],
  "neuro-noise": [
    {
      id: "p1",
      name: "Snowgum",
      mode: "light",
      textColor: "#000000",
      colors: ["#ffffff", "#ccd9d2", "#ecf1ee"],
      speed: 0.4,
      params: { brightness: 0.08, contrast: 0.15 },
    },
    {
      id: "p2",
      name: "Tea Tree",
      mode: "light",
      textColor: "#000000",
      colors: ["#fbfdf9", "#c3d9c0", "#e8f1e5"],
      speed: 0.45,
      params: { brightness: 0.06, contrast: 0.3 },
    },
    {
      id: "p3",
      name: "Coral Shallows",
      mode: "light",
      textColor: "#000000",
      colors: ["#fdf9f6", "#ecc9bc", "#f7e8e0"],
      speed: 0.5,
      params: { brightness: 0.05, contrast: 0.4 },
    },
    {
      id: "p4",
      name: "Hinterland",
      mode: "light",
      textColor: "#000000",
      colors: ["#f9fbfa", "#b8cdc9", "#e4ecea"],
      speed: 0.3,
      params: { brightness: 0.1, contrast: 0.12 },
    },
    {
      id: "p5",
      name: "Bluegum",
      mode: "light",
      textColor: "#000000",
      colors: ["#f9fbfd", "#b5c7d8", "#e2eaf1"],
      speed: 0.4,
      params: { brightness: 0.07, contrast: 0.25 },
    },
    {
      id: "p6",
      name: "Basalt",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#52616f", "#232a32", "#0b0e12"],
      speed: 0.4,
      params: { brightness: 0.07, contrast: 0.35 },
    },
    {
      id: "p7",
      name: "Kimberley Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#85503c", "#301c15", "#100a08"],
      speed: 0.35,
      params: { brightness: 0.06, contrast: 0.45 },
    },
    {
      id: "p8",
      name: "Deep Reef",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#2f6660", "#1a3835", "#081211"],
      speed: 0.45,
      params: { brightness: 0.08, contrast: 0.4 },
    },
    {
      id: "p9",
      name: "Brindabella",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#545a96", "#282b4d", "#0c0d18"],
      speed: 0.5,
      params: { brightness: 0.05, contrast: 0.5 },
    },
  ],
  warp: [
    {
      id: "p1",
      name: "Sandstone",
      mode: "light",
      textColor: "#000000",
      colors: ["#f4ede1", "#e3cfa9", "#ede2cd", "#dcc394"],
      speed: 0.4,
      params: { proportion: 0.5, softness: 1, distortion: 0.2, swirl: 0.6 },
    },
    {
      id: "p2",
      name: "Banksia",
      mode: "light",
      textColor: "#000000",
      colors: ["#f7efe6", "#eccdb0", "#f2e0d0", "#e4b990"],
      speed: 0.35,
      params: { shape: 1, shapeScale: 0.25, swirl: 0.5, softness: 0.85 },
    },
    {
      id: "p3",
      name: "Melaleuca",
      mode: "light",
      textColor: "#000000",
      colors: ["#eff4f0", "#c9dcd0", "#dfe9e2", "#b7d0c1"],
      speed: 0.45,
      params: { shape: 2, shapeScale: 0.2, swirl: 0.7, distortion: 0.3, softness: 0.8 },
    },
    {
      id: "p4",
      name: "High Country",
      mode: "light",
      textColor: "#000000",
      colors: ["#eef2f6", "#c3d3e2", "#dde6ee", "#aec3d6"],
      speed: 0.3,
      params: { proportion: 0.4, softness: 0.9, distortion: 0.35, swirl: 0.9, swirlIterations: 14 },
    },
    {
      id: "p5",
      name: "Freshwater",
      mode: "light",
      textColor: "#000000",
      colors: ["#edf5f5", "#c2e0e0", "#dcedec", "#a9d2d2"],
      speed: 0.5,
      params: { proportion: 0.45, softness: 1, distortion: 0.15, swirl: 0.45 },
    },
    {
      id: "p6",
      name: "Outback Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#140d08", "#6b4a2a", "#2a1c11", "#85582f"],
      speed: 0.4,
      params: { proportion: 0.5, softness: 1, distortion: 0.2, swirl: 0.6 },
    },
    {
      id: "p7",
      name: "Top End",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0a1418", "#25525c", "#132630", "#366a72"],
      speed: 0.45,
      params: { shape: 1, shapeScale: 0.3, swirl: 0.75, softness: 0.8, swirlIterations: 12 },
    },
    {
      id: "p8",
      name: "Blue Mountains",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0d1119", "#3e4a78", "#1a2133", "#4f5d94"],
      speed: 0.3,
      params: { shape: 2, shapeScale: 0.15, swirl: 0.5, distortion: 0.3, softness: 0.9 },
    },
    {
      id: "p9",
      name: "Bogong",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#12100d", "#575145", "#242019", "#665f52"],
      speed: 0.35,
      params: { proportion: 0.55, softness: 0.85, distortion: 0.4, swirl: 1, swirlIterations: 16 },
    },
  ],
  "smoke-ring": [
    {
      id: "p1",
      name: "Ghost Gum",
      mode: "light",
      textColor: "#000000",
      colors: ["#f2f4f1", "#b9c6bb"],
      speed: 0.4,
      params: { thickness: 0.7, radius: 0.25, innerShape: 0.7, noiseScale: 2.6 },
    },
    {
      id: "p2",
      name: "Lake Hillier",
      mode: "light",
      textColor: "#000000",
      colors: ["#f7eef0", "#e3b8c4"],
      speed: 0.35,
      params: { thickness: 0.45, radius: 0.32, innerShape: 1.4, noiseScale: 2 },
    },
    {
      id: "p3",
      name: "Rock Pool",
      mode: "light",
      textColor: "#000000",
      colors: ["#edf4f4", "#a5cbc9"],
      speed: 0.45,
      params: {
        thickness: 0.8,
        radius: 0.22,
        innerShape: 0.5,
        noiseScale: 3.4,
        noiseIterations: 6,
      },
    },
    {
      id: "p4",
      name: "Opal",
      mode: "light",
      textColor: "#000000",
      colors: ["#f1f2f6", "#b3bedd"],
      speed: 0.5,
      params: { thickness: 0.55, radius: 0.3, innerShape: 1, noiseScale: 1.6, noiseIterations: 3 },
    },
    {
      id: "p5",
      name: "Sun Shower",
      mode: "light",
      textColor: "#000000",
      colors: ["#f8f4ea", "#dcc9a0"],
      speed: 0.3,
      params: { thickness: 0.85, radius: 0.2, innerShape: 0.4, noiseScale: 3.8 },
    },
    {
      id: "p6",
      name: "Ningaloo",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#05100f", "#326861"],
      speed: 0.4,
      params: { thickness: 0.65, radius: 0.25, innerShape: 0.7, noiseScale: 2.8 },
    },
    {
      id: "p7",
      name: "Bunya",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0a0f0a", "#46683d"],
      speed: 0.35,
      params: {
        thickness: 0.85,
        radius: 0.2,
        innerShape: 0.45,
        noiseScale: 3.6,
        noiseIterations: 7,
      },
    },
    {
      id: "p8",
      name: "Yarra Night",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#0a0c14", "#525c9c"],
      speed: 0.5,
      params: { thickness: 0.5, radius: 0.32, innerShape: 1.3, noiseScale: 2.2 },
    },
    {
      id: "p9",
      name: "Red Centre",
      mode: "dark",
      textColor: "#ffffff",
      colors: ["#120b08", "#8f4c39"],
      speed: 0.4,
      params: {
        thickness: 0.75,
        radius: 0.24,
        innerShape: 0.55,
        noiseScale: 4.2,
        noiseIterations: 5,
      },
    },
  ],
};
